namespace PTC2024.View.ProfileSettings
{
    partial class FrmProfileConfiguration
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmProfileConfiguration));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.picUser = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuCustomLabel3 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.txtNames = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtLastNames = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuCustomLabel1 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.txtDui = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuCustomLabel2 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.txtPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuCustomLabel4 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.btnSavePhoto = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuCustomLabel5 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.btnChangePassword = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnGuardar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuCustomLabel6 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.txtAffilliation = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuCustomLabel7 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.txtBankA = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuCustomLabel8 = new Bunifu.Framework.UI.BunifuCustomLabel();
            this.snack = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.picUser)).BeginInit();
            this.bunifuPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // picUser
            // 
            this.picUser.AllowFocused = false;
            this.picUser.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.picUser.AutoSizeHeight = false;
            this.picUser.BackColor = System.Drawing.Color.Gainsboro;
            this.picUser.BorderRadius = 96;
            this.picUser.Image = ((System.Drawing.Image)(resources.GetObject("picUser.Image")));
            this.picUser.IsCircle = false;
            this.picUser.Location = new System.Drawing.Point(31, 29);
            this.picUser.Name = "picUser";
            this.picUser.Size = new System.Drawing.Size(192, 192);
            this.picUser.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picUser.TabIndex = 1;
            this.picUser.TabStop = false;
            this.picUser.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuCustomLabel3
            // 
            this.bunifuCustomLabel3.AutoSize = true;
            this.bunifuCustomLabel3.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel3.Location = new System.Drawing.Point(279, 29);
            this.bunifuCustomLabel3.Name = "bunifuCustomLabel3";
            this.bunifuCustomLabel3.Size = new System.Drawing.Size(73, 17);
            this.bunifuCustomLabel3.TabIndex = 34;
            this.bunifuCustomLabel3.Text = "Nombres:";
            // 
            // txtNames
            // 
            this.txtNames.AcceptsReturn = false;
            this.txtNames.AcceptsTab = false;
            this.txtNames.AnimationSpeed = 200;
            this.txtNames.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNames.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNames.AutoSizeHeight = true;
            this.txtNames.BackColor = System.Drawing.Color.LightGray;
            this.txtNames.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNames.BackgroundImage")));
            this.txtNames.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtNames.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNames.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtNames.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.txtNames.BorderRadius = 1;
            this.txtNames.BorderThickness = 3;
            this.txtNames.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtNames.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNames.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNames.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtNames.DefaultText = "";
            this.txtNames.FillColor = System.Drawing.Color.LightGray;
            this.txtNames.HideSelection = true;
            this.txtNames.IconLeft = null;
            this.txtNames.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNames.IconPadding = 10;
            this.txtNames.IconRight = null;
            this.txtNames.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNames.Lines = new string[0];
            this.txtNames.Location = new System.Drawing.Point(282, 49);
            this.txtNames.MaxLength = 150;
            this.txtNames.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNames.Modified = false;
            this.txtNames.Multiline = false;
            this.txtNames.Name = "txtNames";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNames.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNames.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNames.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties36.FillColor = System.Drawing.Color.LightGray;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNames.OnIdleState = stateProperties36;
            this.txtNames.Padding = new System.Windows.Forms.Padding(3);
            this.txtNames.PasswordChar = '\0';
            this.txtNames.PlaceholderForeColor = System.Drawing.Color.LightGray;
            this.txtNames.PlaceholderText = "";
            this.txtNames.ReadOnly = false;
            this.txtNames.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNames.SelectedText = "";
            this.txtNames.SelectionLength = 0;
            this.txtNames.SelectionStart = 0;
            this.txtNames.ShortcutsEnabled = true;
            this.txtNames.Size = new System.Drawing.Size(440, 30);
            this.txtNames.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtNames.TabIndex = 35;
            this.txtNames.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNames.TextMarginBottom = 0;
            this.txtNames.TextMarginLeft = 0;
            this.txtNames.TextMarginTop = 0;
            this.txtNames.TextPlaceholder = "";
            this.txtNames.UseSystemPasswordChar = false;
            this.txtNames.WordWrap = true;
            // 
            // txtLastNames
            // 
            this.txtLastNames.AcceptsReturn = false;
            this.txtLastNames.AcceptsTab = false;
            this.txtLastNames.AnimationSpeed = 200;
            this.txtLastNames.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtLastNames.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtLastNames.AutoSizeHeight = true;
            this.txtLastNames.BackColor = System.Drawing.Color.Gainsboro;
            this.txtLastNames.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtLastNames.BackgroundImage")));
            this.txtLastNames.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtLastNames.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtLastNames.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtLastNames.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.txtLastNames.BorderRadius = 1;
            this.txtLastNames.BorderThickness = 3;
            this.txtLastNames.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtLastNames.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtLastNames.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastNames.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtLastNames.DefaultText = "";
            this.txtLastNames.FillColor = System.Drawing.Color.Gainsboro;
            this.txtLastNames.HideSelection = true;
            this.txtLastNames.IconLeft = null;
            this.txtLastNames.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastNames.IconPadding = 10;
            this.txtLastNames.IconRight = null;
            this.txtLastNames.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtLastNames.Lines = new string[0];
            this.txtLastNames.Location = new System.Drawing.Point(282, 111);
            this.txtLastNames.MaxLength = 150;
            this.txtLastNames.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtLastNames.Modified = false;
            this.txtLastNames.Multiline = false;
            this.txtLastNames.Name = "txtLastNames";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastNames.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtLastNames.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastNames.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties40.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtLastNames.OnIdleState = stateProperties40;
            this.txtLastNames.Padding = new System.Windows.Forms.Padding(3);
            this.txtLastNames.PasswordChar = '\0';
            this.txtLastNames.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtLastNames.PlaceholderText = "";
            this.txtLastNames.ReadOnly = false;
            this.txtLastNames.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtLastNames.SelectedText = "";
            this.txtLastNames.SelectionLength = 0;
            this.txtLastNames.SelectionStart = 0;
            this.txtLastNames.ShortcutsEnabled = true;
            this.txtLastNames.Size = new System.Drawing.Size(440, 30);
            this.txtLastNames.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtLastNames.TabIndex = 37;
            this.txtLastNames.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtLastNames.TextMarginBottom = 0;
            this.txtLastNames.TextMarginLeft = 0;
            this.txtLastNames.TextMarginTop = 0;
            this.txtLastNames.TextPlaceholder = "";
            this.txtLastNames.UseSystemPasswordChar = false;
            this.txtLastNames.WordWrap = true;
            // 
            // bunifuCustomLabel1
            // 
            this.bunifuCustomLabel1.AutoSize = true;
            this.bunifuCustomLabel1.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel1.Location = new System.Drawing.Point(279, 91);
            this.bunifuCustomLabel1.Name = "bunifuCustomLabel1";
            this.bunifuCustomLabel1.Size = new System.Drawing.Size(76, 17);
            this.bunifuCustomLabel1.TabIndex = 36;
            this.bunifuCustomLabel1.Text = "Apellidos:";
            // 
            // txtDui
            // 
            this.txtDui.AcceptsReturn = false;
            this.txtDui.AcceptsTab = false;
            this.txtDui.AnimationSpeed = 200;
            this.txtDui.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDui.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDui.AutoSizeHeight = true;
            this.txtDui.BackColor = System.Drawing.Color.LightGray;
            this.txtDui.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDui.BackgroundImage")));
            this.txtDui.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtDui.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDui.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtDui.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.txtDui.BorderRadius = 1;
            this.txtDui.BorderThickness = 3;
            this.txtDui.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtDui.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDui.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDui.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtDui.DefaultText = "";
            this.txtDui.FillColor = System.Drawing.Color.LightGray;
            this.txtDui.HideSelection = true;
            this.txtDui.IconLeft = null;
            this.txtDui.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDui.IconPadding = 10;
            this.txtDui.IconRight = null;
            this.txtDui.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDui.Lines = new string[0];
            this.txtDui.Location = new System.Drawing.Point(282, 174);
            this.txtDui.MaxLength = 150;
            this.txtDui.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDui.Modified = false;
            this.txtDui.Multiline = false;
            this.txtDui.Name = "txtDui";
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDui.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDui.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDui.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties44.FillColor = System.Drawing.Color.LightGray;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDui.OnIdleState = stateProperties44;
            this.txtDui.Padding = new System.Windows.Forms.Padding(3);
            this.txtDui.PasswordChar = '\0';
            this.txtDui.PlaceholderForeColor = System.Drawing.Color.LightGray;
            this.txtDui.PlaceholderText = "";
            this.txtDui.ReadOnly = false;
            this.txtDui.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDui.SelectedText = "";
            this.txtDui.SelectionLength = 0;
            this.txtDui.SelectionStart = 0;
            this.txtDui.ShortcutsEnabled = true;
            this.txtDui.Size = new System.Drawing.Size(215, 30);
            this.txtDui.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtDui.TabIndex = 39;
            this.txtDui.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDui.TextMarginBottom = 0;
            this.txtDui.TextMarginLeft = 0;
            this.txtDui.TextMarginTop = 0;
            this.txtDui.TextPlaceholder = "";
            this.txtDui.UseSystemPasswordChar = false;
            this.txtDui.WordWrap = true;
            // 
            // bunifuCustomLabel2
            // 
            this.bunifuCustomLabel2.AutoSize = true;
            this.bunifuCustomLabel2.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel2.Location = new System.Drawing.Point(279, 154);
            this.bunifuCustomLabel2.Name = "bunifuCustomLabel2";
            this.bunifuCustomLabel2.Size = new System.Drawing.Size(35, 17);
            this.bunifuCustomLabel2.TabIndex = 38;
            this.bunifuCustomLabel2.Text = "DUI:";
            // 
            // txtPhone
            // 
            this.txtPhone.AcceptsReturn = false;
            this.txtPhone.AcceptsTab = false;
            this.txtPhone.AnimationSpeed = 200;
            this.txtPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtPhone.AutoSizeHeight = true;
            this.txtPhone.BackColor = System.Drawing.Color.LightGray;
            this.txtPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtPhone.BackgroundImage")));
            this.txtPhone.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtPhone.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.txtPhone.BorderRadius = 1;
            this.txtPhone.BorderThickness = 3;
            this.txtPhone.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtPhone.DefaultText = "";
            this.txtPhone.FillColor = System.Drawing.Color.LightGray;
            this.txtPhone.HideSelection = true;
            this.txtPhone.IconLeft = null;
            this.txtPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.IconPadding = 10;
            this.txtPhone.IconRight = null;
            this.txtPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtPhone.Lines = new string[0];
            this.txtPhone.Location = new System.Drawing.Point(507, 174);
            this.txtPhone.MaxLength = 150;
            this.txtPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtPhone.Modified = false;
            this.txtPhone.Multiline = false;
            this.txtPhone.Name = "txtPhone";
            stateProperties45.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtPhone.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties48.FillColor = System.Drawing.Color.LightGray;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtPhone.OnIdleState = stateProperties48;
            this.txtPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtPhone.PasswordChar = '\0';
            this.txtPhone.PlaceholderForeColor = System.Drawing.Color.LightGray;
            this.txtPhone.PlaceholderText = "";
            this.txtPhone.ReadOnly = false;
            this.txtPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtPhone.SelectedText = "";
            this.txtPhone.SelectionLength = 0;
            this.txtPhone.SelectionStart = 0;
            this.txtPhone.ShortcutsEnabled = true;
            this.txtPhone.Size = new System.Drawing.Size(215, 30);
            this.txtPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtPhone.TabIndex = 41;
            this.txtPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtPhone.TextMarginBottom = 0;
            this.txtPhone.TextMarginLeft = 0;
            this.txtPhone.TextMarginTop = 0;
            this.txtPhone.TextPlaceholder = "";
            this.txtPhone.UseSystemPasswordChar = false;
            this.txtPhone.WordWrap = true;
            // 
            // bunifuCustomLabel4
            // 
            this.bunifuCustomLabel4.AutoSize = true;
            this.bunifuCustomLabel4.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel4.Location = new System.Drawing.Point(504, 154);
            this.bunifuCustomLabel4.Name = "bunifuCustomLabel4";
            this.bunifuCustomLabel4.Size = new System.Drawing.Size(70, 17);
            this.bunifuCustomLabel4.TabIndex = 40;
            this.bunifuCustomLabel4.Text = "Teléfono:";
            // 
            // btnSavePhoto
            // 
            this.btnSavePhoto.AllowAnimations = true;
            this.btnSavePhoto.AllowMouseEffects = true;
            this.btnSavePhoto.AllowToggling = false;
            this.btnSavePhoto.AnimationSpeed = 200;
            this.btnSavePhoto.AutoGenerateColors = false;
            this.btnSavePhoto.AutoRoundBorders = true;
            this.btnSavePhoto.AutoSizeLeftIcon = true;
            this.btnSavePhoto.AutoSizeRightIcon = true;
            this.btnSavePhoto.BackColor = System.Drawing.Color.Transparent;
            this.btnSavePhoto.BackColor1 = System.Drawing.Color.DimGray;
            this.btnSavePhoto.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSavePhoto.BackgroundImage")));
            this.btnSavePhoto.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSavePhoto.ButtonText = "Subir foto";
            this.btnSavePhoto.ButtonTextMarginLeft = 0;
            this.btnSavePhoto.ColorContrastOnClick = 45;
            this.btnSavePhoto.ColorContrastOnHover = 45;
            this.btnSavePhoto.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnSavePhoto.CustomizableEdges = borderEdges4;
            this.btnSavePhoto.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSavePhoto.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSavePhoto.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSavePhoto.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSavePhoto.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnSavePhoto.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSavePhoto.ForeColor = System.Drawing.Color.White;
            this.btnSavePhoto.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSavePhoto.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSavePhoto.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSavePhoto.IconMarginLeft = 11;
            this.btnSavePhoto.IconPadding = 10;
            this.btnSavePhoto.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSavePhoto.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSavePhoto.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSavePhoto.IconSize = 25;
            this.btnSavePhoto.IdleBorderColor = System.Drawing.Color.DarkGray;
            this.btnSavePhoto.IdleBorderRadius = 37;
            this.btnSavePhoto.IdleBorderThickness = 1;
            this.btnSavePhoto.IdleFillColor = System.Drawing.Color.DimGray;
            this.btnSavePhoto.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSavePhoto.IdleIconLeftImage")));
            this.btnSavePhoto.IdleIconRightImage = null;
            this.btnSavePhoto.IndicateFocus = false;
            this.btnSavePhoto.Location = new System.Drawing.Point(51, 227);
            this.btnSavePhoto.Name = "btnSavePhoto";
            this.btnSavePhoto.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSavePhoto.OnDisabledState.BorderRadius = 1;
            this.btnSavePhoto.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSavePhoto.OnDisabledState.BorderThickness = 1;
            this.btnSavePhoto.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSavePhoto.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSavePhoto.OnDisabledState.IconLeftImage = null;
            this.btnSavePhoto.OnDisabledState.IconRightImage = null;
            this.btnSavePhoto.onHoverState.BorderColor = System.Drawing.Color.LightGray;
            this.btnSavePhoto.onHoverState.BorderRadius = 1;
            this.btnSavePhoto.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSavePhoto.onHoverState.BorderThickness = 1;
            this.btnSavePhoto.onHoverState.FillColor = System.Drawing.Color.Silver;
            this.btnSavePhoto.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnSavePhoto.onHoverState.IconLeftImage = null;
            this.btnSavePhoto.onHoverState.IconRightImage = null;
            this.btnSavePhoto.OnIdleState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnSavePhoto.OnIdleState.BorderRadius = 1;
            this.btnSavePhoto.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSavePhoto.OnIdleState.BorderThickness = 1;
            this.btnSavePhoto.OnIdleState.FillColor = System.Drawing.Color.DimGray;
            this.btnSavePhoto.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSavePhoto.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnSavePhoto.OnIdleState.IconLeftImage")));
            this.btnSavePhoto.OnIdleState.IconRightImage = null;
            this.btnSavePhoto.OnPressedState.BorderColor = System.Drawing.Color.DarkGray;
            this.btnSavePhoto.OnPressedState.BorderRadius = 1;
            this.btnSavePhoto.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSavePhoto.OnPressedState.BorderThickness = 1;
            this.btnSavePhoto.OnPressedState.FillColor = System.Drawing.Color.DimGray;
            this.btnSavePhoto.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSavePhoto.OnPressedState.IconLeftImage = null;
            this.btnSavePhoto.OnPressedState.IconRightImage = null;
            this.btnSavePhoto.Size = new System.Drawing.Size(150, 39);
            this.btnSavePhoto.TabIndex = 43;
            this.btnSavePhoto.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSavePhoto.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSavePhoto.TextMarginLeft = 0;
            this.btnSavePhoto.TextPadding = new System.Windows.Forms.Padding(0, 0, 29, 0);
            this.btnSavePhoto.UseDefaultRadiusAndThickness = true;
            // 
            // txtEmail
            // 
            this.txtEmail.AcceptsReturn = false;
            this.txtEmail.AcceptsTab = false;
            this.txtEmail.AnimationSpeed = 200;
            this.txtEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmail.AutoSizeHeight = true;
            this.txtEmail.BackColor = System.Drawing.Color.Gainsboro;
            this.txtEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmail.BackgroundImage")));
            this.txtEmail.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtEmail.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.txtEmail.BorderRadius = 1;
            this.txtEmail.BorderThickness = 3;
            this.txtEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtEmail.DefaultText = "";
            this.txtEmail.FillColor = System.Drawing.Color.Gainsboro;
            this.txtEmail.HideSelection = true;
            this.txtEmail.IconLeft = null;
            this.txtEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.IconPadding = 10;
            this.txtEmail.IconRight = null;
            this.txtEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmail.Lines = new string[0];
            this.txtEmail.Location = new System.Drawing.Point(282, 236);
            this.txtEmail.MaxLength = 150;
            this.txtEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmail.Modified = false;
            this.txtEmail.Multiline = false;
            this.txtEmail.Name = "txtEmail";
            stateProperties49.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmail.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties52.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmail.OnIdleState = stateProperties52;
            this.txtEmail.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmail.PasswordChar = '\0';
            this.txtEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtEmail.PlaceholderText = "";
            this.txtEmail.ReadOnly = false;
            this.txtEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmail.SelectedText = "";
            this.txtEmail.SelectionLength = 0;
            this.txtEmail.SelectionStart = 0;
            this.txtEmail.ShortcutsEnabled = true;
            this.txtEmail.Size = new System.Drawing.Size(440, 30);
            this.txtEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtEmail.TabIndex = 45;
            this.txtEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmail.TextMarginBottom = 0;
            this.txtEmail.TextMarginLeft = 0;
            this.txtEmail.TextMarginTop = 0;
            this.txtEmail.TextPlaceholder = "";
            this.txtEmail.UseSystemPasswordChar = false;
            this.txtEmail.WordWrap = true;
            this.txtEmail.TextChanged += new System.EventHandler(this.bunifuTextBox4_TextChanged);
            // 
            // bunifuCustomLabel5
            // 
            this.bunifuCustomLabel5.AutoSize = true;
            this.bunifuCustomLabel5.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel5.Location = new System.Drawing.Point(279, 216);
            this.bunifuCustomLabel5.Name = "bunifuCustomLabel5";
            this.bunifuCustomLabel5.Size = new System.Drawing.Size(140, 17);
            this.bunifuCustomLabel5.TabIndex = 44;
            this.bunifuCustomLabel5.Text = "Correo electrónico:";
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Gainsboro;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.btnChangePassword);
            this.bunifuPanel1.Controls.Add(this.btnGuardar);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 461);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(759, 54);
            this.bunifuPanel1.TabIndex = 46;
            // 
            // btnChangePassword
            // 
            this.btnChangePassword.AllowAnimations = true;
            this.btnChangePassword.AllowMouseEffects = true;
            this.btnChangePassword.AllowToggling = false;
            this.btnChangePassword.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnChangePassword.AnimationSpeed = 200;
            this.btnChangePassword.AutoGenerateColors = false;
            this.btnChangePassword.AutoRoundBorders = true;
            this.btnChangePassword.AutoSizeLeftIcon = true;
            this.btnChangePassword.AutoSizeRightIcon = true;
            this.btnChangePassword.BackColor = System.Drawing.Color.Transparent;
            this.btnChangePassword.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnChangePassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChangePassword.BackgroundImage")));
            this.btnChangePassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnChangePassword.ButtonText = "Cambiar contraseña";
            this.btnChangePassword.ButtonTextMarginLeft = 0;
            this.btnChangePassword.ColorContrastOnClick = 45;
            this.btnChangePassword.ColorContrastOnHover = 45;
            this.btnChangePassword.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnChangePassword.CustomizableEdges = borderEdges5;
            this.btnChangePassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChangePassword.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangePassword.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangePassword.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangePassword.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnChangePassword.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChangePassword.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangePassword.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangePassword.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChangePassword.IconMarginLeft = 11;
            this.btnChangePassword.IconPadding = 10;
            this.btnChangePassword.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangePassword.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChangePassword.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChangePassword.IconSize = 25;
            this.btnChangePassword.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnChangePassword.IdleBorderRadius = 36;
            this.btnChangePassword.IdleBorderThickness = 1;
            this.btnChangePassword.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnChangePassword.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnChangePassword.IdleIconLeftImage")));
            this.btnChangePassword.IdleIconRightImage = null;
            this.btnChangePassword.IndicateFocus = false;
            this.btnChangePassword.Location = new System.Drawing.Point(455, 8);
            this.btnChangePassword.Name = "btnChangePassword";
            this.btnChangePassword.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangePassword.OnDisabledState.BorderRadius = 20;
            this.btnChangePassword.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnChangePassword.OnDisabledState.BorderThickness = 1;
            this.btnChangePassword.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangePassword.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangePassword.OnDisabledState.IconLeftImage = null;
            this.btnChangePassword.OnDisabledState.IconRightImage = null;
            this.btnChangePassword.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnChangePassword.onHoverState.BorderRadius = 20;
            this.btnChangePassword.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnChangePassword.onHoverState.BorderThickness = 1;
            this.btnChangePassword.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnChangePassword.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnChangePassword.onHoverState.IconLeftImage = null;
            this.btnChangePassword.onHoverState.IconRightImage = null;
            this.btnChangePassword.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnChangePassword.OnIdleState.BorderRadius = 20;
            this.btnChangePassword.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnChangePassword.OnIdleState.BorderThickness = 1;
            this.btnChangePassword.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnChangePassword.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnChangePassword.OnIdleState.IconLeftImage")));
            this.btnChangePassword.OnIdleState.IconRightImage = null;
            this.btnChangePassword.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnChangePassword.OnPressedState.BorderRadius = 20;
            this.btnChangePassword.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnChangePassword.OnPressedState.BorderThickness = 1;
            this.btnChangePassword.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnChangePassword.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.OnPressedState.IconLeftImage = null;
            this.btnChangePassword.OnPressedState.IconRightImage = null;
            this.btnChangePassword.Size = new System.Drawing.Size(178, 38);
            this.btnChangePassword.TabIndex = 21;
            this.btnChangePassword.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangePassword.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChangePassword.TextMarginLeft = 0;
            this.btnChangePassword.TextPadding = new System.Windows.Forms.Padding(0, 0, 13, 0);
            this.btnChangePassword.UseDefaultRadiusAndThickness = true;
            this.btnChangePassword.Visible = false;
            // 
            // btnGuardar
            // 
            this.btnGuardar.AllowAnimations = true;
            this.btnGuardar.AllowMouseEffects = true;
            this.btnGuardar.AllowToggling = false;
            this.btnGuardar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnGuardar.AnimationSpeed = 200;
            this.btnGuardar.AutoGenerateColors = false;
            this.btnGuardar.AutoRoundBorders = true;
            this.btnGuardar.AutoSizeLeftIcon = true;
            this.btnGuardar.AutoSizeRightIcon = true;
            this.btnGuardar.BackColor = System.Drawing.Color.Transparent;
            this.btnGuardar.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGuardar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGuardar.BackgroundImage")));
            this.btnGuardar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.ButtonText = "Guardar";
            this.btnGuardar.ButtonTextMarginLeft = 0;
            this.btnGuardar.ColorContrastOnClick = 45;
            this.btnGuardar.ColorContrastOnHover = 45;
            this.btnGuardar.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnGuardar.CustomizableEdges = borderEdges6;
            this.btnGuardar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGuardar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnGuardar.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGuardar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGuardar.IconMarginLeft = 11;
            this.btnGuardar.IconPadding = 10;
            this.btnGuardar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGuardar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGuardar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGuardar.IconSize = 25;
            this.btnGuardar.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGuardar.IdleBorderRadius = 36;
            this.btnGuardar.IdleBorderThickness = 1;
            this.btnGuardar.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGuardar.IdleIconLeftImage = null;
            this.btnGuardar.IdleIconRightImage = null;
            this.btnGuardar.IndicateFocus = false;
            this.btnGuardar.Location = new System.Drawing.Point(639, 8);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGuardar.OnDisabledState.BorderRadius = 20;
            this.btnGuardar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.OnDisabledState.BorderThickness = 1;
            this.btnGuardar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGuardar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGuardar.OnDisabledState.IconLeftImage = null;
            this.btnGuardar.OnDisabledState.IconRightImage = null;
            this.btnGuardar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnGuardar.onHoverState.BorderRadius = 20;
            this.btnGuardar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.onHoverState.BorderThickness = 1;
            this.btnGuardar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnGuardar.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnGuardar.onHoverState.IconLeftImage = null;
            this.btnGuardar.onHoverState.IconRightImage = null;
            this.btnGuardar.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGuardar.OnIdleState.BorderRadius = 20;
            this.btnGuardar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.OnIdleState.BorderThickness = 1;
            this.btnGuardar.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGuardar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.OnIdleState.IconLeftImage = null;
            this.btnGuardar.OnIdleState.IconRightImage = null;
            this.btnGuardar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGuardar.OnPressedState.BorderRadius = 20;
            this.btnGuardar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGuardar.OnPressedState.BorderThickness = 1;
            this.btnGuardar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGuardar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.OnPressedState.IconLeftImage = null;
            this.btnGuardar.OnPressedState.IconRightImage = null;
            this.btnGuardar.Size = new System.Drawing.Size(109, 38);
            this.btnGuardar.TabIndex = 20;
            this.btnGuardar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnGuardar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGuardar.TextMarginLeft = 0;
            this.btnGuardar.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGuardar.UseDefaultRadiusAndThickness = true;
            // 
            // txtAddress
            // 
            this.txtAddress.AcceptsReturn = false;
            this.txtAddress.AcceptsTab = false;
            this.txtAddress.AnimationSpeed = 200;
            this.txtAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAddress.AutoSizeHeight = true;
            this.txtAddress.BackColor = System.Drawing.Color.Gainsboro;
            this.txtAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAddress.BackgroundImage")));
            this.txtAddress.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtAddress.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.txtAddress.BorderRadius = 1;
            this.txtAddress.BorderThickness = 3;
            this.txtAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAddress.DefaultText = "";
            this.txtAddress.FillColor = System.Drawing.Color.Gainsboro;
            this.txtAddress.HideSelection = true;
            this.txtAddress.IconLeft = null;
            this.txtAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.IconPadding = 10;
            this.txtAddress.IconRight = null;
            this.txtAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAddress.Lines = new string[0];
            this.txtAddress.Location = new System.Drawing.Point(31, 308);
            this.txtAddress.MaxLength = 150;
            this.txtAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAddress.Modified = false;
            this.txtAddress.Multiline = true;
            this.txtAddress.Name = "txtAddress";
            stateProperties53.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAddress.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties56.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAddress.OnIdleState = stateProperties56;
            this.txtAddress.Padding = new System.Windows.Forms.Padding(3);
            this.txtAddress.PasswordChar = '\0';
            this.txtAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAddress.PlaceholderText = "";
            this.txtAddress.ReadOnly = false;
            this.txtAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAddress.SelectedText = "";
            this.txtAddress.SelectionLength = 0;
            this.txtAddress.SelectionStart = 0;
            this.txtAddress.ShortcutsEnabled = true;
            this.txtAddress.Size = new System.Drawing.Size(691, 54);
            this.txtAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtAddress.TabIndex = 48;
            this.txtAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAddress.TextMarginBottom = 0;
            this.txtAddress.TextMarginLeft = 0;
            this.txtAddress.TextMarginTop = 0;
            this.txtAddress.TextPlaceholder = "";
            this.txtAddress.UseSystemPasswordChar = false;
            this.txtAddress.WordWrap = true;
            // 
            // bunifuCustomLabel6
            // 
            this.bunifuCustomLabel6.AutoSize = true;
            this.bunifuCustomLabel6.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel6.Location = new System.Drawing.Point(28, 288);
            this.bunifuCustomLabel6.Name = "bunifuCustomLabel6";
            this.bunifuCustomLabel6.Size = new System.Drawing.Size(78, 17);
            this.bunifuCustomLabel6.TabIndex = 47;
            this.bunifuCustomLabel6.Text = "Dirección:";
            // 
            // txtAffilliation
            // 
            this.txtAffilliation.AcceptsReturn = false;
            this.txtAffilliation.AcceptsTab = false;
            this.txtAffilliation.AnimationSpeed = 200;
            this.txtAffilliation.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAffilliation.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAffilliation.AutoSizeHeight = true;
            this.txtAffilliation.BackColor = System.Drawing.Color.Gainsboro;
            this.txtAffilliation.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAffilliation.BackgroundImage")));
            this.txtAffilliation.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtAffilliation.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAffilliation.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtAffilliation.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.txtAffilliation.BorderRadius = 1;
            this.txtAffilliation.BorderThickness = 3;
            this.txtAffilliation.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtAffilliation.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAffilliation.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAffilliation.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAffilliation.DefaultText = "";
            this.txtAffilliation.FillColor = System.Drawing.Color.Gainsboro;
            this.txtAffilliation.HideSelection = true;
            this.txtAffilliation.IconLeft = null;
            this.txtAffilliation.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAffilliation.IconPadding = 10;
            this.txtAffilliation.IconRight = null;
            this.txtAffilliation.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAffilliation.Lines = new string[0];
            this.txtAffilliation.Location = new System.Drawing.Point(31, 398);
            this.txtAffilliation.MaxLength = 150;
            this.txtAffilliation.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAffilliation.Modified = false;
            this.txtAffilliation.Multiline = false;
            this.txtAffilliation.Name = "txtAffilliation";
            stateProperties57.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAffilliation.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAffilliation.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAffilliation.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties60.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAffilliation.OnIdleState = stateProperties60;
            this.txtAffilliation.Padding = new System.Windows.Forms.Padding(3);
            this.txtAffilliation.PasswordChar = '\0';
            this.txtAffilliation.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAffilliation.PlaceholderText = "";
            this.txtAffilliation.ReadOnly = false;
            this.txtAffilliation.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAffilliation.SelectedText = "";
            this.txtAffilliation.SelectionLength = 0;
            this.txtAffilliation.SelectionStart = 0;
            this.txtAffilliation.ShortcutsEnabled = true;
            this.txtAffilliation.Size = new System.Drawing.Size(346, 30);
            this.txtAffilliation.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtAffilliation.TabIndex = 50;
            this.txtAffilliation.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAffilliation.TextMarginBottom = 0;
            this.txtAffilliation.TextMarginLeft = 0;
            this.txtAffilliation.TextMarginTop = 0;
            this.txtAffilliation.TextPlaceholder = "";
            this.txtAffilliation.UseSystemPasswordChar = false;
            this.txtAffilliation.WordWrap = true;
            // 
            // bunifuCustomLabel7
            // 
            this.bunifuCustomLabel7.AutoSize = true;
            this.bunifuCustomLabel7.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel7.Location = new System.Drawing.Point(28, 378);
            this.bunifuCustomLabel7.Name = "bunifuCustomLabel7";
            this.bunifuCustomLabel7.Size = new System.Drawing.Size(138, 17);
            this.bunifuCustomLabel7.TabIndex = 49;
            this.bunifuCustomLabel7.Text = "Núm. de afiliación.";
            // 
            // txtBankA
            // 
            this.txtBankA.AcceptsReturn = false;
            this.txtBankA.AcceptsTab = false;
            this.txtBankA.AnimationSpeed = 200;
            this.txtBankA.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtBankA.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtBankA.AutoSizeHeight = true;
            this.txtBankA.BackColor = System.Drawing.Color.Gainsboro;
            this.txtBankA.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtBankA.BackgroundImage")));
            this.txtBankA.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtBankA.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtBankA.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtBankA.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.txtBankA.BorderRadius = 1;
            this.txtBankA.BorderThickness = 3;
            this.txtBankA.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtBankA.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtBankA.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBankA.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtBankA.DefaultText = "";
            this.txtBankA.FillColor = System.Drawing.Color.Gainsboro;
            this.txtBankA.HideSelection = true;
            this.txtBankA.IconLeft = null;
            this.txtBankA.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBankA.IconPadding = 10;
            this.txtBankA.IconRight = null;
            this.txtBankA.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtBankA.Lines = new string[0];
            this.txtBankA.Location = new System.Drawing.Point(383, 398);
            this.txtBankA.MaxLength = 150;
            this.txtBankA.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtBankA.Modified = false;
            this.txtBankA.Multiline = false;
            this.txtBankA.Name = "txtBankA";
            stateProperties61.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBankA.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtBankA.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBankA.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties64.FillColor = System.Drawing.Color.Gainsboro;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtBankA.OnIdleState = stateProperties64;
            this.txtBankA.Padding = new System.Windows.Forms.Padding(3);
            this.txtBankA.PasswordChar = '\0';
            this.txtBankA.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtBankA.PlaceholderText = "";
            this.txtBankA.ReadOnly = false;
            this.txtBankA.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtBankA.SelectedText = "";
            this.txtBankA.SelectionLength = 0;
            this.txtBankA.SelectionStart = 0;
            this.txtBankA.ShortcutsEnabled = true;
            this.txtBankA.Size = new System.Drawing.Size(339, 30);
            this.txtBankA.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.txtBankA.TabIndex = 52;
            this.txtBankA.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtBankA.TextMarginBottom = 0;
            this.txtBankA.TextMarginLeft = 0;
            this.txtBankA.TextMarginTop = 0;
            this.txtBankA.TextPlaceholder = "";
            this.txtBankA.UseSystemPasswordChar = false;
            this.txtBankA.WordWrap = true;
            // 
            // bunifuCustomLabel8
            // 
            this.bunifuCustomLabel8.AutoSize = true;
            this.bunifuCustomLabel8.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuCustomLabel8.Location = new System.Drawing.Point(380, 378);
            this.bunifuCustomLabel8.Name = "bunifuCustomLabel8";
            this.bunifuCustomLabel8.Size = new System.Drawing.Size(126, 17);
            this.bunifuCustomLabel8.TabIndex = 51;
            this.bunifuCustomLabel8.Text = "Cuenta bancaria:";
            // 
            // snack
            // 
            this.snack.AllowDragging = false;
            this.snack.AllowMultipleViews = true;
            this.snack.ClickToClose = true;
            this.snack.DoubleClickToClose = true;
            this.snack.DurationAfterIdle = 3000;
            this.snack.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snack.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snack.ErrorOptions.ActionBorderRadius = 1;
            this.snack.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snack.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snack.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.snack.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.snack.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.snack.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snack.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.snack.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.snack.ErrorOptions.IconLeftMargin = 12;
            this.snack.FadeCloseIcon = false;
            this.snack.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.snack.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snack.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snack.InformationOptions.ActionBorderRadius = 1;
            this.snack.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snack.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snack.InformationOptions.BackColor = System.Drawing.Color.White;
            this.snack.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.snack.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.snack.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snack.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.snack.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.snack.InformationOptions.IconLeftMargin = 12;
            this.snack.Margin = 10;
            this.snack.MaximumSize = new System.Drawing.Size(0, 0);
            this.snack.MaximumViews = 7;
            this.snack.MessageRightMargin = 15;
            this.snack.MessageTopMargin = 0;
            this.snack.MinimumSize = new System.Drawing.Size(0, 0);
            this.snack.ShowBorders = false;
            this.snack.ShowCloseIcon = false;
            this.snack.ShowIcon = true;
            this.snack.ShowShadows = true;
            this.snack.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snack.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snack.SuccessOptions.ActionBorderRadius = 1;
            this.snack.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snack.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snack.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.snack.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.snack.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.snack.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snack.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.snack.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.snack.SuccessOptions.IconLeftMargin = 12;
            this.snack.ViewsMargin = 7;
            this.snack.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snack.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.snack.WarningOptions.ActionBorderRadius = 1;
            this.snack.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.snack.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.snack.WarningOptions.BackColor = System.Drawing.Color.White;
            this.snack.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.snack.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.snack.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.snack.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.snack.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.snack.WarningOptions.IconLeftMargin = 12;
            this.snack.ZoomCloseIcon = true;
            // 
            // FrmProfileConfiguration
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(759, 515);
            this.Controls.Add(this.txtBankA);
            this.Controls.Add(this.bunifuCustomLabel8);
            this.Controls.Add(this.txtAffilliation);
            this.Controls.Add(this.bunifuCustomLabel7);
            this.Controls.Add(this.txtAddress);
            this.Controls.Add(this.bunifuCustomLabel6);
            this.Controls.Add(this.bunifuPanel1);
            this.Controls.Add(this.txtEmail);
            this.Controls.Add(this.bunifuCustomLabel5);
            this.Controls.Add(this.btnSavePhoto);
            this.Controls.Add(this.txtPhone);
            this.Controls.Add(this.bunifuCustomLabel4);
            this.Controls.Add(this.txtDui);
            this.Controls.Add(this.bunifuCustomLabel2);
            this.Controls.Add(this.txtLastNames);
            this.Controls.Add(this.bunifuCustomLabel1);
            this.Controls.Add(this.txtNames);
            this.Controls.Add(this.bunifuCustomLabel3);
            this.Controls.Add(this.picUser);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.Name = "FrmProfileConfiguration";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Configuración de perfil";
            ((System.ComponentModel.ISupportInitialize)(this.picUser)).EndInit();
            this.bunifuPanel1.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        public Bunifu.UI.WinForms.BunifuPictureBox picUser;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel3;
        public Bunifu.UI.WinForms.BunifuTextBox txtNames;
        public Bunifu.UI.WinForms.BunifuTextBox txtLastNames;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel1;
        public Bunifu.UI.WinForms.BunifuTextBox txtDui;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel2;
        public Bunifu.UI.WinForms.BunifuTextBox txtPhone;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel4;
        public Bunifu.UI.WinForms.BunifuTextBox txtEmail;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel5;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnGuardar;
        public Bunifu.UI.WinForms.BunifuTextBox txtAddress;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel6;
        public Bunifu.UI.WinForms.BunifuTextBox txtAffilliation;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel7;
        public Bunifu.UI.WinForms.BunifuTextBox txtBankA;
        private Bunifu.Framework.UI.BunifuCustomLabel bunifuCustomLabel8;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnChangePassword;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSavePhoto;
        public Bunifu.UI.WinForms.BunifuSnackbar snack;
    }
}