//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTC2024.Resources.Language {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class English {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal English() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTC2024.Resources.Language.English", typeof(English).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add employee.
        /// </summary>
        internal static string addEmployee {
            get {
                return ResourceManager.GetString("addEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add image.
        /// </summary>
        internal static string addImg {
            get {
                return ResourceManager.GetString("addImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administration.
        /// </summary>
        internal static string admin {
            get {
                return ResourceManager.GetString("admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adress:.
        /// </summary>
        internal static string adress {
            get {
                return ResourceManager.GetString("adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Affiliation number.
        /// </summary>
        internal static string affNumber {
            get {
                return ResourceManager.GetString("affNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank:.
        /// </summary>
        internal static string bank {
            get {
                return ResourceManager.GetString("bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bank Account:.
        /// </summary>
        internal static string bankAccount {
            get {
                return ResourceManager.GetString("bankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bills.
        /// </summary>
        internal static string bills {
            get {
                return ResourceManager.GetString("bills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date of Birth:.
        /// </summary>
        internal static string birthDate {
            get {
                return ResourceManager.GetString("birthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BUSINES CONFIGURATION.
        /// </summary>
        internal static string businessConfig {
            get {
                return ResourceManager.GetString("businessConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Business data.
        /// </summary>
        internal static string businessData {
            get {
                return ResourceManager.GetString("businessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Company / Organization Name.
        /// </summary>
        internal static string businessName {
            get {
                return ResourceManager.GetString("businessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Local configuration.
        /// </summary>
        internal static string configBox {
            get {
                return ResourceManager.GetString("configBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm password:.
        /// </summary>
        internal static string confirmPass {
            get {
                return ResourceManager.GetString("confirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creation date:.
        /// </summary>
        internal static string creationDate {
            get {
                return ResourceManager.GetString("creationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Customers.
        /// </summary>
        internal static string customer {
            get {
                return ResourceManager.GetString("customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Audits.
        /// </summary>
        internal static string dashAudits {
            get {
                return ResourceManager.GetString("dashAudits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of bills:.
        /// </summary>
        internal static string dashBillsN {
            get {
                return ResourceManager.GetString("dashBillsN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of costumers:.
        /// </summary>
        internal static string dashCustomerN {
            get {
                return ResourceManager.GetString("dashCustomerN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of employees:.
        /// </summary>
        internal static string dashEmployeeN {
            get {
                return ResourceManager.GetString("dashEmployeeN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payroll / Revenue Summary.
        /// </summary>
        internal static string dashGraphic {
            get {
                return ResourceManager.GetString("dashGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total revenue:.
        /// </summary>
        internal static string dashIncome {
            get {
                return ResourceManager.GetString("dashIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Number of services:.
        /// </summary>
        internal static string dashServicesN {
            get {
                return ResourceManager.GetString("dashServicesN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top Services.
        /// </summary>
        internal static string dashTop {
            get {
                return ResourceManager.GetString("dashTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Base.
        /// </summary>
        internal static string dataBase {
            get {
                return ResourceManager.GetString("dataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Department.
        /// </summary>
        internal static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Develop.
        /// </summary>
        internal static string develop {
            get {
                return ResourceManager.GetString("develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disability.
        /// </summary>
        internal static string disability {
            get {
                return ResourceManager.GetString("disability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable.
        /// </summary>
        internal static string disable {
            get {
                return ResourceManager.GetString("disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disable employee.
        /// </summary>
        internal static string disableEmp {
            get {
                return ResourceManager.GetString("disableEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DUI:.
        /// </summary>
        internal static string DUI {
            get {
                return ResourceManager.GetString("DUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email:.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employees.
        /// </summary>
        internal static string employee {
            get {
                return ResourceManager.GetString("employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View employee record.
        /// </summary>
        internal static string employeeRecord {
            get {
                return ResourceManager.GetString("employeeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right-click on an employee for more options.
        /// </summary>
        internal static string employeeSubTitle {
            get {
                return ResourceManager.GetString("employeeSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Employees.
        /// </summary>
        internal static string employeeTitle {
            get {
                return ResourceManager.GetString("employeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable.
        /// </summary>
        internal static string enable {
            get {
                return ResourceManager.GetString("enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable employee.
        /// </summary>
        internal static string enableEmp {
            get {
                return ResourceManager.GetString("enableEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Financial data.
        /// </summary>
        internal static string financialDat {
            get {
                return ResourceManager.GetString("financialDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot password?.
        /// </summary>
        internal static string forgotP {
            get {
                return ResourceManager.GetString("forgotP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Full time.
        /// </summary>
        internal static string fullTime {
            get {
                return ResourceManager.GetString("fullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gender:.
        /// </summary>
        internal static string gender {
            get {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General report.
        /// </summary>
        internal static string genReport {
            get {
                return ResourceManager.GetString("genReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hire date:.
        /// </summary>
        internal static string hireDate {
            get {
                return ResourceManager.GetString("hireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Human resources.
        /// </summary>
        internal static string humanResources {
            get {
                return ResourceManager.GetString("humanResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Intern.
        /// </summary>
        internal static string interB {
            get {
                return ResourceManager.GetString("interB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Work intern.
        /// </summary>
        internal static string intern {
            get {
                return ResourceManager.GetString("intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last names:.
        /// </summary>
        internal static string lastNames {
            get {
                return ResourceManager.GetString("lastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in data.
        /// </summary>
        internal static string logData {
            get {
                return ResourceManager.GetString("logData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maintenance.
        /// </summary>
        internal static string manteinance {
            get {
                return ResourceManager.GetString("manteinance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marketing.
        /// </summary>
        internal static string marketing {
            get {
                return ResourceManager.GetString("marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maternity.
        /// </summary>
        internal static string Maternity {
            get {
                return ResourceManager.GetString("Maternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Names:.
        /// </summary>
        internal static string names {
            get {
                return ResourceManager.GetString("names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        internal static string passwordForm {
            get {
                return ResourceManager.GetString("passwordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paternity.
        /// </summary>
        internal static string Paternity {
            get {
                return ResourceManager.GetString("Paternity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payrolls.
        /// </summary>
        internal static string payroll {
            get {
                return ResourceManager.GetString("payroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Right-click on a payroll for more options.
        /// </summary>
        internal static string payrollSubTi {
            get {
                return ResourceManager.GetString("payrollSubTi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Payrolls.
        /// </summary>
        internal static string payrollTitle {
            get {
                return ResourceManager.GetString("payrollTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PBX:.
        /// </summary>
        internal static string pbx {
            get {
                return ResourceManager.GetString("pbx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permissions.
        /// </summary>
        internal static string permission {
            get {
                return ResourceManager.GetString("permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal data.
        /// </summary>
        internal static string personalData {
            get {
                return ResourceManager.GetString("personalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Phone:.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign Up.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the information to create a super administrator account..
        /// </summary>
        internal static string registerSubTitle {
            get {
                return ResourceManager.GetString("registerSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember me.
        /// </summary>
        internal static string remember {
            get {
                return ResourceManager.GetString("remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Configuration.
        /// </summary>
        internal static string saveConfigServer {
            get {
                return ResourceManager.GetString("saveConfigServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save info.
        /// </summary>
        internal static string saveinfo {
            get {
                return ResourceManager.GetString("saveinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All.
        /// </summary>
        internal static string searchAll {
            get {
                return ResourceManager.GetString("searchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First trimester.
        /// </summary>
        internal static string searchFirstT {
            get {
                return ResourceManager.GetString("searchFirstT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string searchForm {
            get {
                return ResourceManager.GetString("searchForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server Configuration.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server.
        /// </summary>
        internal static string serverBox {
            get {
                return ResourceManager.GetString("serverBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server URL.
        /// </summary>
        internal static string serverURL {
            get {
                return ResourceManager.GetString("serverURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Services.
        /// </summary>
        internal static string service {
            get {
                return ResourceManager.GetString("service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Technical support.
        /// </summary>
        internal static string tecSupp {
            get {
                return ResourceManager.GetString("tecSupp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the values in each field for the connection to your database..
        /// </summary>
        internal static string titleServer {
            get {
                return ResourceManager.GetString("titleServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows Integrated Security.
        /// </summary>
        internal static string titleServer2 {
            get {
                return ResourceManager.GetString("titleServer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Type employee.
        /// </summary>
        internal static string typeEmployee {
            get {
                return ResourceManager.GetString("typeEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update employee.
        /// </summary>
        internal static string updateEmp {
            get {
                return ResourceManager.GetString("updateEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User:.
        /// </summary>
        internal static string userForm {
            get {
                return ResourceManager.GetString("userForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volunteer.
        /// </summary>
        internal static string volunteer {
            get {
                return ResourceManager.GetString("volunteer", resourceCulture);
            }
        }
    }
}
