namespace PTC2024.View.PasswordRecover
{
    partial class FrmAdminMethod
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmAdminMethod));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.txtAdminPass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtAdminUser = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.label5 = new System.Windows.Forms.Label();
            this.txtUserConfirmPass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.txtUser = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.txtUserNewPass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnConfirm = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.btnVolver = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btnReset = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.ToolTipBoton = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(68, 13);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(397, 39);
            this.bunifuLabel1.TabIndex = 116;
            this.bunifuLabel1.Text = "INGRESE LAS CREDENCIALES DEL ADMINISTRADOR Y LA NUEVA CONTRASEÑA DEL USUARIO";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.ToolTipBoton.SetToolTip(this.bunifuLabel1, "");
            this.ToolTipBoton.SetToolTipIcon(this.bunifuLabel1, null);
            this.ToolTipBoton.SetToolTipTitle(this.bunifuLabel1, "");
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox1.BorderRadius = 5;
            this.bunifuGroupBox1.BorderThickness = 2;
            this.bunifuGroupBox1.Controls.Add(this.label1);
            this.bunifuGroupBox1.Controls.Add(this.label3);
            this.bunifuGroupBox1.Controls.Add(this.txtAdminPass);
            this.bunifuGroupBox1.Controls.Add(this.txtAdminUser);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Century Gothic", 9F);
            this.bunifuGroupBox1.ForeColor = System.Drawing.Color.White;
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(51, 91);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(429, 153);
            this.bunifuGroupBox1.TabIndex = 117;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Credenciales de administrador";
            this.ToolTipBoton.SetToolTip(this.bunifuGroupBox1, "");
            this.ToolTipBoton.SetToolTipIcon(this.bunifuGroupBox1, null);
            this.ToolTipBoton.SetToolTipTitle(this.bunifuGroupBox1, "");
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label1.Location = new System.Drawing.Point(44, 84);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(79, 15);
            this.label1.TabIndex = 129;
            this.label1.Text = "Contraseña:";
            this.ToolTipBoton.SetToolTip(this.label1, "");
            this.ToolTipBoton.SetToolTipIcon(this.label1, null);
            this.ToolTipBoton.SetToolTipTitle(this.label1, "");
            // 
            // label3
            // 
            this.label3.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label3.Location = new System.Drawing.Point(44, 23);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(61, 15);
            this.label3.TabIndex = 128;
            this.label3.Text = "Usuario:";
            this.ToolTipBoton.SetToolTip(this.label3, "");
            this.ToolTipBoton.SetToolTipIcon(this.label3, null);
            this.ToolTipBoton.SetToolTipTitle(this.label3, "");
            // 
            // txtAdminPass
            // 
            this.txtAdminPass.AcceptsReturn = false;
            this.txtAdminPass.AcceptsTab = false;
            this.txtAdminPass.AnimationSpeed = 200;
            this.txtAdminPass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAdminPass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAdminPass.AutoSizeHeight = true;
            this.txtAdminPass.BackColor = System.Drawing.Color.Transparent;
            this.txtAdminPass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAdminPass.BackgroundImage")));
            this.txtAdminPass.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAdminPass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAdminPass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAdminPass.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAdminPass.BorderRadius = 20;
            this.txtAdminPass.BorderThickness = 1;
            this.txtAdminPass.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtAdminPass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAdminPass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdminPass.DefaultFont = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAdminPass.DefaultText = "";
            this.txtAdminPass.FillColor = System.Drawing.Color.White;
            this.txtAdminPass.ForeColor = System.Drawing.Color.Black;
            this.txtAdminPass.HideSelection = true;
            this.txtAdminPass.IconLeft = null;
            this.txtAdminPass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdminPass.IconPadding = 10;
            this.txtAdminPass.IconRight = null;
            this.txtAdminPass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdminPass.Lines = new string[0];
            this.txtAdminPass.Location = new System.Drawing.Point(39, 102);
            this.txtAdminPass.MaximumSize = new System.Drawing.Size(358, 32);
            this.txtAdminPass.MaxLength = 32767;
            this.txtAdminPass.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAdminPass.Modified = false;
            this.txtAdminPass.Multiline = false;
            this.txtAdminPass.Name = "txtAdminPass";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdminPass.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAdminPass.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdminPass.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Black;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdminPass.OnIdleState = stateProperties4;
            this.txtAdminPass.Padding = new System.Windows.Forms.Padding(3);
            this.txtAdminPass.PasswordChar = '\0';
            this.txtAdminPass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAdminPass.PlaceholderText = "";
            this.txtAdminPass.ReadOnly = false;
            this.txtAdminPass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAdminPass.SelectedText = "";
            this.txtAdminPass.SelectionLength = 0;
            this.txtAdminPass.SelectionStart = 0;
            this.txtAdminPass.ShortcutsEnabled = true;
            this.txtAdminPass.Size = new System.Drawing.Size(358, 32);
            this.txtAdminPass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAdminPass.TabIndex = 127;
            this.txtAdminPass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAdminPass.TextMarginBottom = 0;
            this.txtAdminPass.TextMarginLeft = 3;
            this.txtAdminPass.TextMarginTop = 1;
            this.txtAdminPass.TextPlaceholder = "";
            this.ToolTipBoton.SetToolTip(this.txtAdminPass, "");
            this.ToolTipBoton.SetToolTipIcon(this.txtAdminPass, null);
            this.ToolTipBoton.SetToolTipTitle(this.txtAdminPass, "");
            this.txtAdminPass.UseSystemPasswordChar = true;
            this.txtAdminPass.WordWrap = true;
            // 
            // txtAdminUser
            // 
            this.txtAdminUser.AcceptsReturn = false;
            this.txtAdminUser.AcceptsTab = false;
            this.txtAdminUser.AnimationSpeed = 200;
            this.txtAdminUser.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtAdminUser.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtAdminUser.AutoSizeHeight = true;
            this.txtAdminUser.BackColor = System.Drawing.Color.Transparent;
            this.txtAdminUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtAdminUser.BackgroundImage")));
            this.txtAdminUser.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtAdminUser.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtAdminUser.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtAdminUser.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtAdminUser.BorderRadius = 20;
            this.txtAdminUser.BorderThickness = 1;
            this.txtAdminUser.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtAdminUser.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtAdminUser.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdminUser.DefaultFont = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtAdminUser.DefaultText = "";
            this.txtAdminUser.FillColor = System.Drawing.Color.White;
            this.txtAdminUser.ForeColor = System.Drawing.Color.Black;
            this.txtAdminUser.HideSelection = true;
            this.txtAdminUser.IconLeft = null;
            this.txtAdminUser.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdminUser.IconPadding = 10;
            this.txtAdminUser.IconRight = null;
            this.txtAdminUser.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtAdminUser.Lines = new string[0];
            this.txtAdminUser.Location = new System.Drawing.Point(39, 41);
            this.txtAdminUser.MaximumSize = new System.Drawing.Size(358, 32);
            this.txtAdminUser.MaxLength = 32767;
            this.txtAdminUser.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtAdminUser.Modified = false;
            this.txtAdminUser.Multiline = false;
            this.txtAdminUser.Name = "txtAdminUser";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdminUser.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtAdminUser.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdminUser.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Black;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtAdminUser.OnIdleState = stateProperties8;
            this.txtAdminUser.Padding = new System.Windows.Forms.Padding(3);
            this.txtAdminUser.PasswordChar = '\0';
            this.txtAdminUser.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtAdminUser.PlaceholderText = "";
            this.txtAdminUser.ReadOnly = false;
            this.txtAdminUser.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtAdminUser.SelectedText = "";
            this.txtAdminUser.SelectionLength = 0;
            this.txtAdminUser.SelectionStart = 0;
            this.txtAdminUser.ShortcutsEnabled = true;
            this.txtAdminUser.Size = new System.Drawing.Size(358, 32);
            this.txtAdminUser.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtAdminUser.TabIndex = 126;
            this.txtAdminUser.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtAdminUser.TextMarginBottom = 0;
            this.txtAdminUser.TextMarginLeft = 3;
            this.txtAdminUser.TextMarginTop = 1;
            this.txtAdminUser.TextPlaceholder = "";
            this.ToolTipBoton.SetToolTip(this.txtAdminUser, "");
            this.ToolTipBoton.SetToolTipIcon(this.txtAdminUser, null);
            this.ToolTipBoton.SetToolTipTitle(this.txtAdminUser, "");
            this.txtAdminUser.UseSystemPasswordChar = false;
            this.txtAdminUser.WordWrap = true;
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.LightGray;
            this.bunifuGroupBox2.BorderRadius = 5;
            this.bunifuGroupBox2.BorderThickness = 2;
            this.bunifuGroupBox2.Controls.Add(this.label5);
            this.bunifuGroupBox2.Controls.Add(this.txtUserConfirmPass);
            this.bunifuGroupBox2.Controls.Add(this.label2);
            this.bunifuGroupBox2.Controls.Add(this.txtUser);
            this.bunifuGroupBox2.Controls.Add(this.label4);
            this.bunifuGroupBox2.Controls.Add(this.txtUserNewPass);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Century Gothic", 9F);
            this.bunifuGroupBox2.ForeColor = System.Drawing.Color.White;
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(51, 260);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(429, 210);
            this.bunifuGroupBox2.TabIndex = 118;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Credenciales del usuario";
            this.ToolTipBoton.SetToolTip(this.bunifuGroupBox2, "");
            this.ToolTipBoton.SetToolTipIcon(this.bunifuGroupBox2, null);
            this.ToolTipBoton.SetToolTipTitle(this.bunifuGroupBox2, "");
            // 
            // label5
            // 
            this.label5.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label5.Location = new System.Drawing.Point(44, 142);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(139, 15);
            this.label5.TabIndex = 135;
            this.label5.Text = "Confirmar contraseña:";
            this.ToolTipBoton.SetToolTip(this.label5, "");
            this.ToolTipBoton.SetToolTipIcon(this.label5, null);
            this.ToolTipBoton.SetToolTipTitle(this.label5, "");
            // 
            // txtUserConfirmPass
            // 
            this.txtUserConfirmPass.AcceptsReturn = false;
            this.txtUserConfirmPass.AcceptsTab = false;
            this.txtUserConfirmPass.AnimationSpeed = 200;
            this.txtUserConfirmPass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUserConfirmPass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUserConfirmPass.AutoSizeHeight = true;
            this.txtUserConfirmPass.BackColor = System.Drawing.Color.Transparent;
            this.txtUserConfirmPass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUserConfirmPass.BackgroundImage")));
            this.txtUserConfirmPass.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUserConfirmPass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUserConfirmPass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUserConfirmPass.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUserConfirmPass.BorderRadius = 20;
            this.txtUserConfirmPass.BorderThickness = 1;
            this.txtUserConfirmPass.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUserConfirmPass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUserConfirmPass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserConfirmPass.DefaultFont = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUserConfirmPass.DefaultText = "";
            this.txtUserConfirmPass.FillColor = System.Drawing.Color.White;
            this.txtUserConfirmPass.ForeColor = System.Drawing.Color.Black;
            this.txtUserConfirmPass.HideSelection = true;
            this.txtUserConfirmPass.IconLeft = null;
            this.txtUserConfirmPass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserConfirmPass.IconPadding = 10;
            this.txtUserConfirmPass.IconRight = null;
            this.txtUserConfirmPass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserConfirmPass.Lines = new string[0];
            this.txtUserConfirmPass.Location = new System.Drawing.Point(39, 160);
            this.txtUserConfirmPass.MaximumSize = new System.Drawing.Size(358, 32);
            this.txtUserConfirmPass.MaxLength = 32767;
            this.txtUserConfirmPass.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUserConfirmPass.Modified = false;
            this.txtUserConfirmPass.Multiline = false;
            this.txtUserConfirmPass.Name = "txtUserConfirmPass";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserConfirmPass.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUserConfirmPass.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserConfirmPass.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Black;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserConfirmPass.OnIdleState = stateProperties12;
            this.txtUserConfirmPass.Padding = new System.Windows.Forms.Padding(3);
            this.txtUserConfirmPass.PasswordChar = '\0';
            this.txtUserConfirmPass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUserConfirmPass.PlaceholderText = "";
            this.txtUserConfirmPass.ReadOnly = false;
            this.txtUserConfirmPass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUserConfirmPass.SelectedText = "";
            this.txtUserConfirmPass.SelectionLength = 0;
            this.txtUserConfirmPass.SelectionStart = 0;
            this.txtUserConfirmPass.ShortcutsEnabled = true;
            this.txtUserConfirmPass.Size = new System.Drawing.Size(358, 32);
            this.txtUserConfirmPass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUserConfirmPass.TabIndex = 134;
            this.txtUserConfirmPass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUserConfirmPass.TextMarginBottom = 0;
            this.txtUserConfirmPass.TextMarginLeft = 3;
            this.txtUserConfirmPass.TextMarginTop = 1;
            this.txtUserConfirmPass.TextPlaceholder = "";
            this.ToolTipBoton.SetToolTip(this.txtUserConfirmPass, "");
            this.ToolTipBoton.SetToolTipIcon(this.txtUserConfirmPass, null);
            this.ToolTipBoton.SetToolTipTitle(this.txtUserConfirmPass, "");
            this.txtUserConfirmPass.UseSystemPasswordChar = true;
            this.txtUserConfirmPass.WordWrap = true;
            // 
            // label2
            // 
            this.label2.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label2.Location = new System.Drawing.Point(44, 82);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(123, 15);
            this.label2.TabIndex = 133;
            this.label2.Text = "Nueva contraseña:";
            this.ToolTipBoton.SetToolTip(this.label2, "");
            this.ToolTipBoton.SetToolTipIcon(this.label2, null);
            this.ToolTipBoton.SetToolTipTitle(this.label2, "");
            // 
            // txtUser
            // 
            this.txtUser.AcceptsReturn = false;
            this.txtUser.AcceptsTab = false;
            this.txtUser.AnimationSpeed = 200;
            this.txtUser.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUser.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUser.AutoSizeHeight = true;
            this.txtUser.BackColor = System.Drawing.Color.Transparent;
            this.txtUser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUser.BackgroundImage")));
            this.txtUser.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUser.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUser.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUser.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUser.BorderRadius = 20;
            this.txtUser.BorderThickness = 1;
            this.txtUser.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUser.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUser.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUser.DefaultFont = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUser.DefaultText = "";
            this.txtUser.FillColor = System.Drawing.Color.White;
            this.txtUser.ForeColor = System.Drawing.Color.Black;
            this.txtUser.HideSelection = true;
            this.txtUser.IconLeft = null;
            this.txtUser.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUser.IconPadding = 10;
            this.txtUser.IconRight = null;
            this.txtUser.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUser.Lines = new string[0];
            this.txtUser.Location = new System.Drawing.Point(39, 40);
            this.txtUser.MaximumSize = new System.Drawing.Size(358, 32);
            this.txtUser.MaxLength = 32767;
            this.txtUser.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUser.Modified = false;
            this.txtUser.Multiline = false;
            this.txtUser.Name = "txtUser";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUser.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUser.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUser.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Black;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUser.OnIdleState = stateProperties16;
            this.txtUser.Padding = new System.Windows.Forms.Padding(3);
            this.txtUser.PasswordChar = '\0';
            this.txtUser.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUser.PlaceholderText = "";
            this.txtUser.ReadOnly = false;
            this.txtUser.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUser.SelectedText = "";
            this.txtUser.SelectionLength = 0;
            this.txtUser.SelectionStart = 0;
            this.txtUser.ShortcutsEnabled = true;
            this.txtUser.Size = new System.Drawing.Size(358, 32);
            this.txtUser.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUser.TabIndex = 130;
            this.txtUser.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUser.TextMarginBottom = 0;
            this.txtUser.TextMarginLeft = 3;
            this.txtUser.TextMarginTop = 1;
            this.txtUser.TextPlaceholder = "";
            this.ToolTipBoton.SetToolTip(this.txtUser, "");
            this.ToolTipBoton.SetToolTipIcon(this.txtUser, null);
            this.ToolTipBoton.SetToolTipTitle(this.txtUser, "");
            this.txtUser.UseSystemPasswordChar = false;
            this.txtUser.WordWrap = true;
            // 
            // label4
            // 
            this.label4.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.ForeColor = System.Drawing.SystemColors.ButtonFace;
            this.label4.Location = new System.Drawing.Point(44, 22);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(61, 15);
            this.label4.TabIndex = 132;
            this.label4.Text = "Usuario:";
            this.ToolTipBoton.SetToolTip(this.label4, "");
            this.ToolTipBoton.SetToolTipIcon(this.label4, null);
            this.ToolTipBoton.SetToolTipTitle(this.label4, "");
            // 
            // txtUserNewPass
            // 
            this.txtUserNewPass.AcceptsReturn = false;
            this.txtUserNewPass.AcceptsTab = false;
            this.txtUserNewPass.AnimationSpeed = 200;
            this.txtUserNewPass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtUserNewPass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtUserNewPass.AutoSizeHeight = true;
            this.txtUserNewPass.BackColor = System.Drawing.Color.Transparent;
            this.txtUserNewPass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtUserNewPass.BackgroundImage")));
            this.txtUserNewPass.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtUserNewPass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtUserNewPass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtUserNewPass.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtUserNewPass.BorderRadius = 20;
            this.txtUserNewPass.BorderThickness = 1;
            this.txtUserNewPass.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtUserNewPass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtUserNewPass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserNewPass.DefaultFont = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtUserNewPass.DefaultText = "";
            this.txtUserNewPass.FillColor = System.Drawing.Color.White;
            this.txtUserNewPass.ForeColor = System.Drawing.Color.Black;
            this.txtUserNewPass.HideSelection = true;
            this.txtUserNewPass.IconLeft = null;
            this.txtUserNewPass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserNewPass.IconPadding = 10;
            this.txtUserNewPass.IconRight = null;
            this.txtUserNewPass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtUserNewPass.Lines = new string[0];
            this.txtUserNewPass.Location = new System.Drawing.Point(39, 100);
            this.txtUserNewPass.MaximumSize = new System.Drawing.Size(358, 32);
            this.txtUserNewPass.MaxLength = 32767;
            this.txtUserNewPass.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtUserNewPass.Modified = false;
            this.txtUserNewPass.Multiline = false;
            this.txtUserNewPass.Name = "txtUserNewPass";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserNewPass.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtUserNewPass.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserNewPass.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Black;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtUserNewPass.OnIdleState = stateProperties20;
            this.txtUserNewPass.Padding = new System.Windows.Forms.Padding(3);
            this.txtUserNewPass.PasswordChar = '\0';
            this.txtUserNewPass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtUserNewPass.PlaceholderText = "";
            this.txtUserNewPass.ReadOnly = false;
            this.txtUserNewPass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtUserNewPass.SelectedText = "";
            this.txtUserNewPass.SelectionLength = 0;
            this.txtUserNewPass.SelectionStart = 0;
            this.txtUserNewPass.ShortcutsEnabled = true;
            this.txtUserNewPass.Size = new System.Drawing.Size(358, 32);
            this.txtUserNewPass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtUserNewPass.TabIndex = 131;
            this.txtUserNewPass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtUserNewPass.TextMarginBottom = 0;
            this.txtUserNewPass.TextMarginLeft = 3;
            this.txtUserNewPass.TextMarginTop = 1;
            this.txtUserNewPass.TextPlaceholder = "";
            this.ToolTipBoton.SetToolTip(this.txtUserNewPass, "");
            this.ToolTipBoton.SetToolTipIcon(this.txtUserNewPass, null);
            this.ToolTipBoton.SetToolTipTitle(this.txtUserNewPass, "");
            this.txtUserNewPass.UseSystemPasswordChar = true;
            this.txtUserNewPass.WordWrap = true;
            // 
            // btnConfirm
            // 
            this.btnConfirm.AllowAnimations = true;
            this.btnConfirm.AllowMouseEffects = true;
            this.btnConfirm.AllowToggling = false;
            this.btnConfirm.AnimationSpeed = 200;
            this.btnConfirm.AutoGenerateColors = false;
            this.btnConfirm.AutoRoundBorders = false;
            this.btnConfirm.AutoSizeLeftIcon = true;
            this.btnConfirm.AutoSizeRightIcon = true;
            this.btnConfirm.BackColor = System.Drawing.Color.Transparent;
            this.btnConfirm.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnConfirm.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnConfirm.BackgroundImage")));
            this.btnConfirm.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConfirm.ButtonText = "Confirmar";
            this.btnConfirm.ButtonTextMarginLeft = 0;
            this.btnConfirm.ColorContrastOnClick = 45;
            this.btnConfirm.ColorContrastOnHover = 45;
            this.btnConfirm.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnConfirm.CustomizableEdges = borderEdges1;
            this.btnConfirm.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnConfirm.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfirm.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConfirm.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConfirm.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnConfirm.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnConfirm.ForeColor = System.Drawing.Color.White;
            this.btnConfirm.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnConfirm.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfirm.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnConfirm.IconMarginLeft = 11;
            this.btnConfirm.IconPadding = 10;
            this.btnConfirm.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnConfirm.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnConfirm.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnConfirm.IconSize = 25;
            this.btnConfirm.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnConfirm.IdleBorderRadius = 20;
            this.btnConfirm.IdleBorderThickness = 1;
            this.btnConfirm.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnConfirm.IdleIconLeftImage = null;
            this.btnConfirm.IdleIconRightImage = null;
            this.btnConfirm.IndicateFocus = false;
            this.btnConfirm.Location = new System.Drawing.Point(263, 492);
            this.btnConfirm.Name = "btnConfirm";
            this.btnConfirm.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnConfirm.OnDisabledState.BorderRadius = 20;
            this.btnConfirm.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConfirm.OnDisabledState.BorderThickness = 1;
            this.btnConfirm.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnConfirm.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnConfirm.OnDisabledState.IconLeftImage = null;
            this.btnConfirm.OnDisabledState.IconRightImage = null;
            this.btnConfirm.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnConfirm.onHoverState.BorderRadius = 20;
            this.btnConfirm.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConfirm.onHoverState.BorderThickness = 1;
            this.btnConfirm.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnConfirm.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnConfirm.onHoverState.IconLeftImage = null;
            this.btnConfirm.onHoverState.IconRightImage = null;
            this.btnConfirm.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnConfirm.OnIdleState.BorderRadius = 20;
            this.btnConfirm.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConfirm.OnIdleState.BorderThickness = 1;
            this.btnConfirm.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnConfirm.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnConfirm.OnIdleState.IconLeftImage = null;
            this.btnConfirm.OnIdleState.IconRightImage = null;
            this.btnConfirm.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnConfirm.OnPressedState.BorderRadius = 20;
            this.btnConfirm.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnConfirm.OnPressedState.BorderThickness = 1;
            this.btnConfirm.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnConfirm.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnConfirm.OnPressedState.IconLeftImage = null;
            this.btnConfirm.OnPressedState.IconRightImage = null;
            this.btnConfirm.Size = new System.Drawing.Size(159, 40);
            this.btnConfirm.TabIndex = 122;
            this.btnConfirm.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnConfirm.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnConfirm.TextMarginLeft = 0;
            this.btnConfirm.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTipBoton.SetToolTip(this.btnConfirm, "");
            this.ToolTipBoton.SetToolTipIcon(this.btnConfirm, null);
            this.ToolTipBoton.SetToolTipTitle(this.btnConfirm, "");
            this.btnConfirm.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Dash;
            this.bunifuSeparator1.LineThickness = 2;
            this.bunifuSeparator1.Location = new System.Drawing.Point(51, 58);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(429, 21);
            this.bunifuSeparator1.TabIndex = 121;
            this.ToolTipBoton.SetToolTip(this.bunifuSeparator1, "");
            this.ToolTipBoton.SetToolTipIcon(this.bunifuSeparator1, null);
            this.ToolTipBoton.SetToolTipTitle(this.bunifuSeparator1, "");
            // 
            // btnVolver
            // 
            this.btnVolver.ActiveImage = null;
            this.btnVolver.AllowAnimations = true;
            this.btnVolver.AllowBuffering = false;
            this.btnVolver.AllowToggling = false;
            this.btnVolver.AllowZooming = true;
            this.btnVolver.AllowZoomingOnFocus = false;
            this.btnVolver.BackColor = System.Drawing.Color.Transparent;
            this.btnVolver.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVolver.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnVolver.ErrorImage")));
            this.btnVolver.FadeWhenInactive = false;
            this.btnVolver.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnVolver.Image = ((System.Drawing.Image)(resources.GetObject("btnVolver.Image")));
            this.btnVolver.ImageActive = null;
            this.btnVolver.ImageLocation = null;
            this.btnVolver.ImageMargin = 20;
            this.btnVolver.ImageSize = new System.Drawing.Size(20, 20);
            this.btnVolver.ImageZoomSize = new System.Drawing.Size(40, 40);
            this.btnVolver.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnVolver.InitialImage")));
            this.btnVolver.Location = new System.Drawing.Point(12, 12);
            this.btnVolver.Name = "btnVolver";
            this.btnVolver.Rotation = 0;
            this.btnVolver.ShowActiveImage = true;
            this.btnVolver.ShowCursorChanges = true;
            this.btnVolver.ShowImageBorders = true;
            this.btnVolver.ShowSizeMarkers = false;
            this.btnVolver.Size = new System.Drawing.Size(40, 40);
            this.btnVolver.TabIndex = 115;
            this.ToolTipBoton.SetToolTip(this.btnVolver, "");
            this.ToolTipBoton.SetToolTipIcon(this.btnVolver, null);
            this.btnVolver.ToolTipText = "";
            this.ToolTipBoton.SetToolTipTitle(this.btnVolver, "");
            this.btnVolver.WaitOnLoad = false;
            this.btnVolver.Zoom = 20;
            this.btnVolver.ZoomSpeed = 10;
            // 
            // btnReset
            // 
            this.btnReset.AllowAnimations = true;
            this.btnReset.AllowMouseEffects = true;
            this.btnReset.AllowToggling = false;
            this.btnReset.AnimationSpeed = 200;
            this.btnReset.AutoGenerateColors = false;
            this.btnReset.AutoRoundBorders = false;
            this.btnReset.AutoSizeLeftIcon = true;
            this.btnReset.AutoSizeRightIcon = true;
            this.btnReset.BackColor = System.Drawing.Color.Transparent;
            this.btnReset.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnReset.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReset.BackgroundImage")));
            this.btnReset.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReset.ButtonText = "Solo restablecer";
            this.btnReset.ButtonTextMarginLeft = 0;
            this.btnReset.ColorContrastOnClick = 45;
            this.btnReset.ColorContrastOnHover = 45;
            this.btnReset.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnReset.CustomizableEdges = borderEdges2;
            this.btnReset.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReset.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReset.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReset.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReset.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnReset.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnReset.ForeColor = System.Drawing.Color.White;
            this.btnReset.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReset.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnReset.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnReset.IconMarginLeft = 11;
            this.btnReset.IconPadding = 10;
            this.btnReset.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnReset.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnReset.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnReset.IconSize = 25;
            this.btnReset.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnReset.IdleBorderRadius = 20;
            this.btnReset.IdleBorderThickness = 1;
            this.btnReset.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnReset.IdleIconLeftImage = null;
            this.btnReset.IdleIconRightImage = null;
            this.btnReset.IndicateFocus = false;
            this.btnReset.Location = new System.Drawing.Point(98, 492);
            this.btnReset.Name = "btnReset";
            this.btnReset.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReset.OnDisabledState.BorderRadius = 20;
            this.btnReset.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReset.OnDisabledState.BorderThickness = 1;
            this.btnReset.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReset.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReset.OnDisabledState.IconLeftImage = null;
            this.btnReset.OnDisabledState.IconRightImage = null;
            this.btnReset.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReset.onHoverState.BorderRadius = 20;
            this.btnReset.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReset.onHoverState.BorderThickness = 1;
            this.btnReset.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReset.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnReset.onHoverState.IconLeftImage = null;
            this.btnReset.onHoverState.IconRightImage = null;
            this.btnReset.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnReset.OnIdleState.BorderRadius = 20;
            this.btnReset.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReset.OnIdleState.BorderThickness = 1;
            this.btnReset.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnReset.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnReset.OnIdleState.IconLeftImage = null;
            this.btnReset.OnIdleState.IconRightImage = null;
            this.btnReset.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnReset.OnPressedState.BorderRadius = 20;
            this.btnReset.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReset.OnPressedState.BorderThickness = 1;
            this.btnReset.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(178)))), ((int)(((byte)(53)))));
            this.btnReset.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnReset.OnPressedState.IconLeftImage = null;
            this.btnReset.OnPressedState.IconRightImage = null;
            this.btnReset.Size = new System.Drawing.Size(159, 40);
            this.btnReset.TabIndex = 123;
            this.btnReset.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnReset.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnReset.TextMarginLeft = 0;
            this.btnReset.TextPadding = new System.Windows.Forms.Padding(0);
            this.ToolTipBoton.SetToolTip(this.btnReset, "Presione este botón si no desea una contraseña personalizada y solo restablecerla" +
        ".");
            this.ToolTipBoton.SetToolTipIcon(this.btnReset, null);
            this.ToolTipBoton.SetToolTipTitle(this.btnReset, "Restablecer contraseña");
            this.btnReset.UseDefaultRadiusAndThickness = true;
            // 
            // ToolTipBoton
            // 
            this.ToolTipBoton.Active = true;
            this.ToolTipBoton.AlignTextWithTitle = false;
            this.ToolTipBoton.AllowAutoClose = false;
            this.ToolTipBoton.AllowFading = true;
            this.ToolTipBoton.AutoCloseDuration = 5000;
            this.ToolTipBoton.BackColor = System.Drawing.SystemColors.Control;
            this.ToolTipBoton.BorderColor = System.Drawing.Color.Gainsboro;
            this.ToolTipBoton.ClickToShowDisplayControl = false;
            this.ToolTipBoton.ConvertNewlinesToBreakTags = true;
            this.ToolTipBoton.DisplayControl = null;
            this.ToolTipBoton.EntryAnimationSpeed = 350;
            this.ToolTipBoton.ExitAnimationSpeed = 200;
            this.ToolTipBoton.GenerateAutoCloseDuration = false;
            this.ToolTipBoton.IconMargin = 6;
            this.ToolTipBoton.InitialDelay = 0;
            this.ToolTipBoton.Name = "ToolTipBoton";
            this.ToolTipBoton.Opacity = 1D;
            this.ToolTipBoton.OverrideToolTipTitles = false;
            this.ToolTipBoton.Padding = new System.Windows.Forms.Padding(10);
            this.ToolTipBoton.ReshowDelay = 100;
            this.ToolTipBoton.ShowAlways = true;
            this.ToolTipBoton.ShowBorders = false;
            this.ToolTipBoton.ShowIcons = true;
            this.ToolTipBoton.ShowShadows = true;
            this.ToolTipBoton.Tag = null;
            this.ToolTipBoton.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.ToolTipBoton.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.ToolTipBoton.TextMargin = 2;
            this.ToolTipBoton.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.ToolTipBoton.TitleForeColor = System.Drawing.Color.Black;
            this.ToolTipBoton.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.ToolTipBoton.ToolTipTitle = null;
            // 
            // FrmAdminMethod
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(193)))), ((int)(((byte)(46)))), ((int)(((byte)(33)))));
            this.ClientSize = new System.Drawing.Size(520, 553);
            this.Controls.Add(this.btnReset);
            this.Controls.Add(this.btnConfirm);
            this.Controls.Add(this.bunifuSeparator1);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.btnVolver);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FrmAdminMethod";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "FrmAdminMethod";
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        public Bunifu.UI.WinForms.BunifuImageButton btnVolver;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label3;
        public Bunifu.UI.WinForms.BunifuTextBox txtAdminPass;
        public Bunifu.UI.WinForms.BunifuTextBox txtAdminUser;
        private System.Windows.Forms.Label label5;
        public Bunifu.UI.WinForms.BunifuTextBox txtUserConfirmPass;
        private System.Windows.Forms.Label label2;
        public Bunifu.UI.WinForms.BunifuTextBox txtUser;
        private System.Windows.Forms.Label label4;
        public Bunifu.UI.WinForms.BunifuTextBox txtUserNewPass;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnConfirm;
        private Bunifu.UI.WinForms.BunifuToolTip ToolTipBoton;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnReset;
    }
}