namespace PTC2024.View.Service_inventory
{
    partial class prueba
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(prueba));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.picNotification = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.btnReportCustomers = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.BtnAddCustomer = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.BtnAddEmployee = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnGeneralReport = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.txtEmployeeSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnAddService = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnReportServices = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.picNotification)).BeginInit();
            this.SuspendLayout();
            // 
            // picNotification
            // 
            this.picNotification.AllowFocused = false;
            this.picNotification.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.picNotification.AutoSizeHeight = false;
            this.picNotification.BorderRadius = 30;
            this.picNotification.Image = ((System.Drawing.Image)(resources.GetObject("picNotification.Image")));
            this.picNotification.IsCircle = true;
            this.picNotification.Location = new System.Drawing.Point(116, 198);
            this.picNotification.Name = "picNotification";
            this.picNotification.Size = new System.Drawing.Size(61, 61);
            this.picNotification.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picNotification.TabIndex = 101;
            this.picNotification.TabStop = false;
            this.picNotification.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // btnReportCustomers
            // 
            this.btnReportCustomers.AllowAnimations = true;
            this.btnReportCustomers.AllowMouseEffects = true;
            this.btnReportCustomers.AllowToggling = false;
            this.btnReportCustomers.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnReportCustomers.AnimationSpeed = 200;
            this.btnReportCustomers.AutoGenerateColors = false;
            this.btnReportCustomers.AutoRoundBorders = false;
            this.btnReportCustomers.AutoSizeLeftIcon = true;
            this.btnReportCustomers.AutoSizeRightIcon = true;
            this.btnReportCustomers.BackColor = System.Drawing.Color.Transparent;
            this.btnReportCustomers.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportCustomers.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReportCustomers.BackgroundImage")));
            this.btnReportCustomers.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportCustomers.ButtonText = "Reporte general";
            this.btnReportCustomers.ButtonTextMarginLeft = 0;
            this.btnReportCustomers.ColorContrastOnClick = 45;
            this.btnReportCustomers.ColorContrastOnHover = 45;
            this.btnReportCustomers.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnReportCustomers.CustomizableEdges = borderEdges1;
            this.btnReportCustomers.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReportCustomers.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReportCustomers.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReportCustomers.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReportCustomers.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnReportCustomers.Font = new System.Drawing.Font("Century Gothic", 10F);
            this.btnReportCustomers.ForeColor = System.Drawing.Color.White;
            this.btnReportCustomers.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReportCustomers.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnReportCustomers.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnReportCustomers.IconMarginLeft = 11;
            this.btnReportCustomers.IconPadding = 10;
            this.btnReportCustomers.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReportCustomers.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnReportCustomers.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnReportCustomers.IconSize = 25;
            this.btnReportCustomers.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportCustomers.IdleBorderRadius = 15;
            this.btnReportCustomers.IdleBorderThickness = 1;
            this.btnReportCustomers.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportCustomers.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnReportCustomers.IdleIconLeftImage")));
            this.btnReportCustomers.IdleIconRightImage = null;
            this.btnReportCustomers.IndicateFocus = false;
            this.btnReportCustomers.Location = new System.Drawing.Point(100, 342);
            this.btnReportCustomers.Name = "btnReportCustomers";
            this.btnReportCustomers.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReportCustomers.OnDisabledState.BorderRadius = 15;
            this.btnReportCustomers.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportCustomers.OnDisabledState.BorderThickness = 1;
            this.btnReportCustomers.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReportCustomers.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReportCustomers.OnDisabledState.IconLeftImage = null;
            this.btnReportCustomers.OnDisabledState.IconRightImage = null;
            this.btnReportCustomers.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReportCustomers.onHoverState.BorderRadius = 15;
            this.btnReportCustomers.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportCustomers.onHoverState.BorderThickness = 1;
            this.btnReportCustomers.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReportCustomers.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnReportCustomers.onHoverState.IconLeftImage = null;
            this.btnReportCustomers.onHoverState.IconRightImage = null;
            this.btnReportCustomers.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportCustomers.OnIdleState.BorderRadius = 15;
            this.btnReportCustomers.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportCustomers.OnIdleState.BorderThickness = 1;
            this.btnReportCustomers.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportCustomers.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnReportCustomers.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnReportCustomers.OnIdleState.IconLeftImage")));
            this.btnReportCustomers.OnIdleState.IconRightImage = null;
            this.btnReportCustomers.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReportCustomers.OnPressedState.BorderRadius = 15;
            this.btnReportCustomers.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportCustomers.OnPressedState.BorderThickness = 1;
            this.btnReportCustomers.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReportCustomers.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnReportCustomers.OnPressedState.IconLeftImage = null;
            this.btnReportCustomers.OnPressedState.IconRightImage = null;
            this.btnReportCustomers.Size = new System.Drawing.Size(179, 51);
            this.btnReportCustomers.TabIndex = 104;
            this.btnReportCustomers.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnReportCustomers.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnReportCustomers.TextMarginLeft = 0;
            this.btnReportCustomers.TextPadding = new System.Windows.Forms.Padding(0, 0, 7, 0);
            this.btnReportCustomers.UseDefaultRadiusAndThickness = true;
            // 
            // BtnAddCustomer
            // 
            this.BtnAddCustomer.AllowAnimations = true;
            this.BtnAddCustomer.AllowMouseEffects = true;
            this.BtnAddCustomer.AllowToggling = false;
            this.BtnAddCustomer.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.BtnAddCustomer.AnimationSpeed = 200;
            this.BtnAddCustomer.AutoGenerateColors = false;
            this.BtnAddCustomer.AutoRoundBorders = false;
            this.BtnAddCustomer.AutoSizeLeftIcon = true;
            this.BtnAddCustomer.AutoSizeRightIcon = true;
            this.BtnAddCustomer.BackColor = System.Drawing.Color.Transparent;
            this.BtnAddCustomer.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddCustomer.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnAddCustomer.BackgroundImage")));
            this.BtnAddCustomer.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddCustomer.ButtonText = "Agregar cliente";
            this.BtnAddCustomer.ButtonTextMarginLeft = 0;
            this.BtnAddCustomer.ColorContrastOnClick = 45;
            this.BtnAddCustomer.ColorContrastOnHover = 45;
            this.BtnAddCustomer.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnAddCustomer.CustomizableEdges = borderEdges2;
            this.BtnAddCustomer.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnAddCustomer.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAddCustomer.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAddCustomer.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAddCustomer.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.BtnAddCustomer.Font = new System.Drawing.Font("Century Gothic", 10F);
            this.BtnAddCustomer.ForeColor = System.Drawing.Color.White;
            this.BtnAddCustomer.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAddCustomer.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAddCustomer.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnAddCustomer.IconMarginLeft = 11;
            this.BtnAddCustomer.IconPadding = 10;
            this.BtnAddCustomer.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAddCustomer.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAddCustomer.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnAddCustomer.IconSize = 25;
            this.BtnAddCustomer.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddCustomer.IdleBorderRadius = 15;
            this.BtnAddCustomer.IdleBorderThickness = 1;
            this.BtnAddCustomer.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddCustomer.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("BtnAddCustomer.IdleIconLeftImage")));
            this.BtnAddCustomer.IdleIconRightImage = null;
            this.BtnAddCustomer.IndicateFocus = false;
            this.BtnAddCustomer.Location = new System.Drawing.Point(136, 285);
            this.BtnAddCustomer.Name = "BtnAddCustomer";
            this.BtnAddCustomer.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAddCustomer.OnDisabledState.BorderRadius = 15;
            this.BtnAddCustomer.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddCustomer.OnDisabledState.BorderThickness = 1;
            this.BtnAddCustomer.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAddCustomer.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAddCustomer.OnDisabledState.IconLeftImage = null;
            this.BtnAddCustomer.OnDisabledState.IconRightImage = null;
            this.BtnAddCustomer.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.BtnAddCustomer.onHoverState.BorderRadius = 15;
            this.BtnAddCustomer.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddCustomer.onHoverState.BorderThickness = 1;
            this.BtnAddCustomer.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.BtnAddCustomer.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnAddCustomer.onHoverState.IconLeftImage = null;
            this.BtnAddCustomer.onHoverState.IconRightImage = null;
            this.BtnAddCustomer.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddCustomer.OnIdleState.BorderRadius = 15;
            this.BtnAddCustomer.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddCustomer.OnIdleState.BorderThickness = 1;
            this.BtnAddCustomer.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddCustomer.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnAddCustomer.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("BtnAddCustomer.OnIdleState.IconLeftImage")));
            this.BtnAddCustomer.OnIdleState.IconRightImage = null;
            this.BtnAddCustomer.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.BtnAddCustomer.OnPressedState.BorderRadius = 15;
            this.BtnAddCustomer.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddCustomer.OnPressedState.BorderThickness = 1;
            this.BtnAddCustomer.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.BtnAddCustomer.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.BtnAddCustomer.OnPressedState.IconLeftImage = null;
            this.BtnAddCustomer.OnPressedState.IconRightImage = null;
            this.BtnAddCustomer.Size = new System.Drawing.Size(179, 51);
            this.BtnAddCustomer.TabIndex = 105;
            this.BtnAddCustomer.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnAddCustomer.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnAddCustomer.TextMarginLeft = 0;
            this.BtnAddCustomer.TextPadding = new System.Windows.Forms.Padding(0, 0, 7, 0);
            this.BtnAddCustomer.UseDefaultRadiusAndThickness = true;
            // 
            // BtnAddEmployee
            // 
            this.BtnAddEmployee.AllowAnimations = true;
            this.BtnAddEmployee.AllowMouseEffects = true;
            this.BtnAddEmployee.AllowToggling = false;
            this.BtnAddEmployee.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.BtnAddEmployee.AnimationSpeed = 200;
            this.BtnAddEmployee.AutoGenerateColors = false;
            this.BtnAddEmployee.AutoRoundBorders = false;
            this.BtnAddEmployee.AutoSizeLeftIcon = true;
            this.BtnAddEmployee.AutoSizeRightIcon = true;
            this.BtnAddEmployee.BackColor = System.Drawing.Color.Transparent;
            this.BtnAddEmployee.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddEmployee.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnAddEmployee.BackgroundImage")));
            this.BtnAddEmployee.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddEmployee.ButtonText = "Agregar empleado";
            this.BtnAddEmployee.ButtonTextMarginLeft = 0;
            this.BtnAddEmployee.ColorContrastOnClick = 45;
            this.BtnAddEmployee.ColorContrastOnHover = 45;
            this.BtnAddEmployee.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnAddEmployee.CustomizableEdges = borderEdges3;
            this.BtnAddEmployee.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnAddEmployee.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAddEmployee.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAddEmployee.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAddEmployee.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.BtnAddEmployee.Font = new System.Drawing.Font("Century Gothic", 10F);
            this.BtnAddEmployee.ForeColor = System.Drawing.Color.White;
            this.BtnAddEmployee.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAddEmployee.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAddEmployee.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnAddEmployee.IconMarginLeft = 11;
            this.BtnAddEmployee.IconPadding = 10;
            this.BtnAddEmployee.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAddEmployee.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAddEmployee.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnAddEmployee.IconSize = 25;
            this.BtnAddEmployee.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddEmployee.IdleBorderRadius = 15;
            this.BtnAddEmployee.IdleBorderThickness = 1;
            this.BtnAddEmployee.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddEmployee.IdleIconLeftImage = global::PTC2024.Properties.Resources.AgregarEmpleado;
            this.BtnAddEmployee.IdleIconRightImage = null;
            this.BtnAddEmployee.IndicateFocus = false;
            this.BtnAddEmployee.Location = new System.Drawing.Point(335, 316);
            this.BtnAddEmployee.Name = "BtnAddEmployee";
            this.BtnAddEmployee.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAddEmployee.OnDisabledState.BorderRadius = 15;
            this.BtnAddEmployee.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddEmployee.OnDisabledState.BorderThickness = 1;
            this.BtnAddEmployee.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAddEmployee.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAddEmployee.OnDisabledState.IconLeftImage = null;
            this.BtnAddEmployee.OnDisabledState.IconRightImage = null;
            this.BtnAddEmployee.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.BtnAddEmployee.onHoverState.BorderRadius = 15;
            this.BtnAddEmployee.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddEmployee.onHoverState.BorderThickness = 1;
            this.BtnAddEmployee.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.BtnAddEmployee.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.BtnAddEmployee.onHoverState.IconLeftImage = null;
            this.BtnAddEmployee.onHoverState.IconRightImage = null;
            this.BtnAddEmployee.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddEmployee.OnIdleState.BorderRadius = 15;
            this.BtnAddEmployee.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddEmployee.OnIdleState.BorderThickness = 1;
            this.BtnAddEmployee.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddEmployee.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnAddEmployee.OnIdleState.IconLeftImage = global::PTC2024.Properties.Resources.AgregarEmpleado;
            this.BtnAddEmployee.OnIdleState.IconRightImage = null;
            this.BtnAddEmployee.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddEmployee.OnPressedState.BorderRadius = 15;
            this.BtnAddEmployee.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.BtnAddEmployee.OnPressedState.BorderThickness = 1;
            this.BtnAddEmployee.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.BtnAddEmployee.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnAddEmployee.OnPressedState.IconLeftImage = null;
            this.BtnAddEmployee.OnPressedState.IconRightImage = null;
            this.BtnAddEmployee.Size = new System.Drawing.Size(197, 51);
            this.BtnAddEmployee.TabIndex = 106;
            this.BtnAddEmployee.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnAddEmployee.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnAddEmployee.TextMarginLeft = 0;
            this.BtnAddEmployee.TextPadding = new System.Windows.Forms.Padding(0, 0, 7, 0);
            this.BtnAddEmployee.UseDefaultRadiusAndThickness = true;
            // 
            // btnGeneralReport
            // 
            this.btnGeneralReport.AllowAnimations = true;
            this.btnGeneralReport.AllowMouseEffects = true;
            this.btnGeneralReport.AllowToggling = false;
            this.btnGeneralReport.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnGeneralReport.AnimationSpeed = 200;
            this.btnGeneralReport.AutoGenerateColors = false;
            this.btnGeneralReport.AutoRoundBorders = false;
            this.btnGeneralReport.AutoSizeLeftIcon = true;
            this.btnGeneralReport.AutoSizeRightIcon = true;
            this.btnGeneralReport.BackColor = System.Drawing.Color.Transparent;
            this.btnGeneralReport.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGeneralReport.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGeneralReport.BackgroundImage")));
            this.btnGeneralReport.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGeneralReport.ButtonText = "Reporte general";
            this.btnGeneralReport.ButtonTextMarginLeft = 0;
            this.btnGeneralReport.ColorContrastOnClick = 45;
            this.btnGeneralReport.ColorContrastOnHover = 45;
            this.btnGeneralReport.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnGeneralReport.CustomizableEdges = borderEdges4;
            this.btnGeneralReport.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGeneralReport.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGeneralReport.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGeneralReport.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGeneralReport.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnGeneralReport.Font = new System.Drawing.Font("Century Gothic", 10F);
            this.btnGeneralReport.ForeColor = System.Drawing.Color.White;
            this.btnGeneralReport.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGeneralReport.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGeneralReport.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGeneralReport.IconMarginLeft = 11;
            this.btnGeneralReport.IconPadding = 10;
            this.btnGeneralReport.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGeneralReport.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGeneralReport.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGeneralReport.IconSize = 25;
            this.btnGeneralReport.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGeneralReport.IdleBorderRadius = 15;
            this.btnGeneralReport.IdleBorderThickness = 1;
            this.btnGeneralReport.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGeneralReport.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnGeneralReport.IdleIconLeftImage")));
            this.btnGeneralReport.IdleIconRightImage = null;
            this.btnGeneralReport.IndicateFocus = false;
            this.btnGeneralReport.Location = new System.Drawing.Point(310, 228);
            this.btnGeneralReport.Name = "btnGeneralReport";
            this.btnGeneralReport.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGeneralReport.OnDisabledState.BorderRadius = 15;
            this.btnGeneralReport.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGeneralReport.OnDisabledState.BorderThickness = 1;
            this.btnGeneralReport.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGeneralReport.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGeneralReport.OnDisabledState.IconLeftImage = null;
            this.btnGeneralReport.OnDisabledState.IconRightImage = null;
            this.btnGeneralReport.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnGeneralReport.onHoverState.BorderRadius = 15;
            this.btnGeneralReport.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGeneralReport.onHoverState.BorderThickness = 1;
            this.btnGeneralReport.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnGeneralReport.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnGeneralReport.onHoverState.IconLeftImage = null;
            this.btnGeneralReport.onHoverState.IconRightImage = null;
            this.btnGeneralReport.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGeneralReport.OnIdleState.BorderRadius = 15;
            this.btnGeneralReport.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGeneralReport.OnIdleState.BorderThickness = 1;
            this.btnGeneralReport.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGeneralReport.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnGeneralReport.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnGeneralReport.OnIdleState.IconLeftImage")));
            this.btnGeneralReport.OnIdleState.IconRightImage = null;
            this.btnGeneralReport.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGeneralReport.OnPressedState.BorderRadius = 15;
            this.btnGeneralReport.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnGeneralReport.OnPressedState.BorderThickness = 1;
            this.btnGeneralReport.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnGeneralReport.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGeneralReport.OnPressedState.IconLeftImage = null;
            this.btnGeneralReport.OnPressedState.IconRightImage = null;
            this.btnGeneralReport.Size = new System.Drawing.Size(197, 51);
            this.btnGeneralReport.TabIndex = 107;
            this.btnGeneralReport.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGeneralReport.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGeneralReport.TextMarginLeft = 0;
            this.btnGeneralReport.TextPadding = new System.Windows.Forms.Padding(0, 0, 19, 0);
            this.btnGeneralReport.UseDefaultRadiusAndThickness = true;
            // 
            // txtEmployeeSearch
            // 
            this.txtEmployeeSearch.AcceptsReturn = false;
            this.txtEmployeeSearch.AcceptsTab = false;
            this.txtEmployeeSearch.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtEmployeeSearch.AnimationSpeed = 200;
            this.txtEmployeeSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtEmployeeSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtEmployeeSearch.AutoSizeHeight = true;
            this.txtEmployeeSearch.BackColor = System.Drawing.Color.Transparent;
            this.txtEmployeeSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtEmployeeSearch.BackgroundImage")));
            this.txtEmployeeSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtEmployeeSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtEmployeeSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtEmployeeSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtEmployeeSearch.BorderRadius = 20;
            this.txtEmployeeSearch.BorderThickness = 1;
            this.txtEmployeeSearch.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtEmployeeSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtEmployeeSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmployeeSearch.DefaultFont = new System.Drawing.Font("Century Gothic", 9.25F);
            this.txtEmployeeSearch.DefaultText = "";
            this.txtEmployeeSearch.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtEmployeeSearch.ForeColor = System.Drawing.Color.White;
            this.txtEmployeeSearch.HideSelection = true;
            this.txtEmployeeSearch.IconLeft = null;
            this.txtEmployeeSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmployeeSearch.IconPadding = 10;
            this.txtEmployeeSearch.IconRight = ((System.Drawing.Image)(resources.GetObject("txtEmployeeSearch.IconRight")));
            this.txtEmployeeSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtEmployeeSearch.Lines = new string[0];
            this.txtEmployeeSearch.Location = new System.Drawing.Point(64, 94);
            this.txtEmployeeSearch.MaxLength = 32767;
            this.txtEmployeeSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtEmployeeSearch.Modified = false;
            this.txtEmployeeSearch.Multiline = false;
            this.txtEmployeeSearch.Name = "txtEmployeeSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmployeeSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtEmployeeSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmployeeSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtEmployeeSearch.OnIdleState = stateProperties4;
            this.txtEmployeeSearch.Padding = new System.Windows.Forms.Padding(3);
            this.txtEmployeeSearch.PasswordChar = '\0';
            this.txtEmployeeSearch.PlaceholderForeColor = System.Drawing.Color.White;
            this.txtEmployeeSearch.PlaceholderText = "Buscar un empleado...";
            this.txtEmployeeSearch.ReadOnly = false;
            this.txtEmployeeSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtEmployeeSearch.SelectedText = "";
            this.txtEmployeeSearch.SelectionLength = 0;
            this.txtEmployeeSearch.SelectionStart = 0;
            this.txtEmployeeSearch.ShortcutsEnabled = true;
            this.txtEmployeeSearch.Size = new System.Drawing.Size(564, 39);
            this.txtEmployeeSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtEmployeeSearch.TabIndex = 108;
            this.txtEmployeeSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtEmployeeSearch.TextMarginBottom = 0;
            this.txtEmployeeSearch.TextMarginLeft = 3;
            this.txtEmployeeSearch.TextMarginTop = 1;
            this.txtEmployeeSearch.TextPlaceholder = "Buscar un empleado...";
            this.txtEmployeeSearch.UseSystemPasswordChar = false;
            this.txtEmployeeSearch.WordWrap = true;
            // 
            // btnAddService
            // 
            this.btnAddService.AllowAnimations = true;
            this.btnAddService.AllowMouseEffects = true;
            this.btnAddService.AllowToggling = false;
            this.btnAddService.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnAddService.AnimationSpeed = 200;
            this.btnAddService.AutoGenerateColors = false;
            this.btnAddService.AutoRoundBorders = false;
            this.btnAddService.AutoSizeLeftIcon = true;
            this.btnAddService.AutoSizeRightIcon = true;
            this.btnAddService.BackColor = System.Drawing.Color.Transparent;
            this.btnAddService.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAddService.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAddService.BackgroundImage")));
            this.btnAddService.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddService.ButtonText = "Agregar servicio";
            this.btnAddService.ButtonTextMarginLeft = 0;
            this.btnAddService.ColorContrastOnClick = 45;
            this.btnAddService.ColorContrastOnHover = 45;
            this.btnAddService.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnAddService.CustomizableEdges = borderEdges5;
            this.btnAddService.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAddService.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddService.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddService.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddService.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAddService.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAddService.ForeColor = System.Drawing.Color.White;
            this.btnAddService.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddService.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddService.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAddService.IconMarginLeft = 11;
            this.btnAddService.IconPadding = 10;
            this.btnAddService.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAddService.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAddService.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAddService.IconSize = 25;
            this.btnAddService.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAddService.IdleBorderRadius = 15;
            this.btnAddService.IdleBorderThickness = 1;
            this.btnAddService.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAddService.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAddService.IdleIconLeftImage")));
            this.btnAddService.IdleIconRightImage = null;
            this.btnAddService.IndicateFocus = false;
            this.btnAddService.Location = new System.Drawing.Point(806, 186);
            this.btnAddService.Name = "btnAddService";
            this.btnAddService.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAddService.OnDisabledState.BorderRadius = 15;
            this.btnAddService.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddService.OnDisabledState.BorderThickness = 1;
            this.btnAddService.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAddService.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAddService.OnDisabledState.IconLeftImage = null;
            this.btnAddService.OnDisabledState.IconRightImage = null;
            this.btnAddService.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnAddService.onHoverState.BorderRadius = 15;
            this.btnAddService.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddService.onHoverState.BorderThickness = 1;
            this.btnAddService.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnAddService.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnAddService.onHoverState.IconLeftImage = null;
            this.btnAddService.onHoverState.IconRightImage = null;
            this.btnAddService.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAddService.OnIdleState.BorderRadius = 15;
            this.btnAddService.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddService.OnIdleState.BorderThickness = 1;
            this.btnAddService.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAddService.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAddService.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAddService.OnIdleState.IconLeftImage")));
            this.btnAddService.OnIdleState.IconRightImage = null;
            this.btnAddService.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnAddService.OnPressedState.BorderRadius = 15;
            this.btnAddService.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAddService.OnPressedState.BorderThickness = 1;
            this.btnAddService.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnAddService.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnAddService.OnPressedState.IconLeftImage = null;
            this.btnAddService.OnPressedState.IconRightImage = null;
            this.btnAddService.Size = new System.Drawing.Size(197, 51);
            this.btnAddService.TabIndex = 109;
            this.btnAddService.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAddService.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAddService.TextMarginLeft = 0;
            this.btnAddService.TextPadding = new System.Windows.Forms.Padding(0, 0, 7, 0);
            this.btnAddService.UseDefaultRadiusAndThickness = true;
            // 
            // btnReportServices
            // 
            this.btnReportServices.AllowAnimations = true;
            this.btnReportServices.AllowMouseEffects = true;
            this.btnReportServices.AllowToggling = false;
            this.btnReportServices.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.btnReportServices.AnimationSpeed = 200;
            this.btnReportServices.AutoGenerateColors = false;
            this.btnReportServices.AutoRoundBorders = false;
            this.btnReportServices.AutoSizeLeftIcon = true;
            this.btnReportServices.AutoSizeRightIcon = true;
            this.btnReportServices.BackColor = System.Drawing.Color.Transparent;
            this.btnReportServices.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportServices.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReportServices.BackgroundImage")));
            this.btnReportServices.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportServices.ButtonText = "Reporte de Servicios";
            this.btnReportServices.ButtonTextMarginLeft = 0;
            this.btnReportServices.ColorContrastOnClick = 45;
            this.btnReportServices.ColorContrastOnHover = 45;
            this.btnReportServices.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnReportServices.CustomizableEdges = borderEdges6;
            this.btnReportServices.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReportServices.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReportServices.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReportServices.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReportServices.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnReportServices.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnReportServices.ForeColor = System.Drawing.Color.White;
            this.btnReportServices.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReportServices.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnReportServices.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnReportServices.IconMarginLeft = 11;
            this.btnReportServices.IconPadding = 10;
            this.btnReportServices.IconRightAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnReportServices.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnReportServices.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnReportServices.IconSize = 25;
            this.btnReportServices.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportServices.IdleBorderRadius = 15;
            this.btnReportServices.IdleBorderThickness = 1;
            this.btnReportServices.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportServices.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnReportServices.IdleIconLeftImage")));
            this.btnReportServices.IdleIconRightImage = null;
            this.btnReportServices.IndicateFocus = false;
            this.btnReportServices.Location = new System.Drawing.Point(806, 243);
            this.btnReportServices.Name = "btnReportServices";
            this.btnReportServices.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReportServices.OnDisabledState.BorderRadius = 15;
            this.btnReportServices.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportServices.OnDisabledState.BorderThickness = 1;
            this.btnReportServices.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReportServices.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReportServices.OnDisabledState.IconLeftImage = null;
            this.btnReportServices.OnDisabledState.IconRightImage = null;
            this.btnReportServices.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReportServices.onHoverState.BorderRadius = 15;
            this.btnReportServices.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportServices.onHoverState.BorderThickness = 1;
            this.btnReportServices.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReportServices.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnReportServices.onHoverState.IconLeftImage = null;
            this.btnReportServices.onHoverState.IconRightImage = null;
            this.btnReportServices.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportServices.OnIdleState.BorderRadius = 15;
            this.btnReportServices.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportServices.OnIdleState.BorderThickness = 1;
            this.btnReportServices.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnReportServices.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnReportServices.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnReportServices.OnIdleState.IconLeftImage")));
            this.btnReportServices.OnIdleState.IconRightImage = null;
            this.btnReportServices.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReportServices.OnPressedState.BorderRadius = 15;
            this.btnReportServices.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnReportServices.OnPressedState.BorderThickness = 1;
            this.btnReportServices.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnReportServices.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnReportServices.OnPressedState.IconLeftImage = null;
            this.btnReportServices.OnPressedState.IconRightImage = null;
            this.btnReportServices.Size = new System.Drawing.Size(197, 51);
            this.btnReportServices.TabIndex = 110;
            this.btnReportServices.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnReportServices.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnReportServices.TextMarginLeft = 0;
            this.btnReportServices.TextPadding = new System.Windows.Forms.Padding(0, 0, 7, 0);
            this.btnReportServices.UseDefaultRadiusAndThickness = true;
            // 
            // prueba
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1162, 450);
            this.Controls.Add(this.btnReportServices);
            this.Controls.Add(this.btnAddService);
            this.Controls.Add(this.txtEmployeeSearch);
            this.Controls.Add(this.btnGeneralReport);
            this.Controls.Add(this.BtnAddEmployee);
            this.Controls.Add(this.BtnAddCustomer);
            this.Controls.Add(this.btnReportCustomers);
            this.Controls.Add(this.picNotification);
            this.Name = "prueba";
            this.Text = "prueba";
            ((System.ComponentModel.ISupportInitialize)(this.picNotification)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        public Bunifu.UI.WinForms.BunifuPictureBox picNotification;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnReportCustomers;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 BtnAddCustomer;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 BtnAddEmployee;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnGeneralReport;
        public Bunifu.UI.WinForms.BunifuTextBox txtEmployeeSearch;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAddService;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnReportServices;
    }
}