namespace PTC2024.View.Service_inventory
{
    partial class prueba
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(prueba));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.tableLayoutPanel17 = new System.Windows.Forms.TableLayoutPanel();
            this.btnFourth = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnAll = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnFirstT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnThirtht = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnSecondT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.picNotification = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.txtSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tableLayoutPanel17.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picNotification)).BeginInit();
            this.SuspendLayout();
            // 
            // tableLayoutPanel17
            // 
            this.tableLayoutPanel17.ColumnCount = 5;
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel17.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 20F));
            this.tableLayoutPanel17.Controls.Add(this.btnFourth, 3, 0);
            this.tableLayoutPanel17.Controls.Add(this.btnAll, 0, 0);
            this.tableLayoutPanel17.Controls.Add(this.btnFirstT, 1, 0);
            this.tableLayoutPanel17.Controls.Add(this.btnThirtht, 4, 0);
            this.tableLayoutPanel17.Controls.Add(this.btnSecondT, 2, 0);
            this.tableLayoutPanel17.Location = new System.Drawing.Point(8, 8);
            this.tableLayoutPanel17.Name = "tableLayoutPanel17";
            this.tableLayoutPanel17.RowCount = 1;
            this.tableLayoutPanel17.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel17.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel17.Size = new System.Drawing.Size(627, 67);
            this.tableLayoutPanel17.TabIndex = 100;
            // 
            // btnFourth
            // 
            this.btnFourth.AllowAnimations = true;
            this.btnFourth.AllowMouseEffects = true;
            this.btnFourth.AllowToggling = false;
            this.btnFourth.AnimationSpeed = 200;
            this.btnFourth.AutoGenerateColors = false;
            this.btnFourth.AutoRoundBorders = false;
            this.btnFourth.AutoSizeLeftIcon = true;
            this.btnFourth.AutoSizeRightIcon = true;
            this.btnFourth.BackColor = System.Drawing.Color.Transparent;
            this.btnFourth.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFourth.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFourth.BackgroundImage")));
            this.btnFourth.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFourth.ButtonText = "Cuarto trimestre";
            this.btnFourth.ButtonTextMarginLeft = 0;
            this.btnFourth.ColorContrastOnClick = 45;
            this.btnFourth.ColorContrastOnHover = 45;
            this.btnFourth.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnFourth.CustomizableEdges = borderEdges1;
            this.btnFourth.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFourth.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFourth.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFourth.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFourth.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnFourth.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnFourth.ForeColor = System.Drawing.Color.White;
            this.btnFourth.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFourth.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFourth.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFourth.IconMarginLeft = 11;
            this.btnFourth.IconPadding = 10;
            this.btnFourth.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFourth.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFourth.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFourth.IconSize = 25;
            this.btnFourth.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFourth.IdleBorderRadius = 20;
            this.btnFourth.IdleBorderThickness = 1;
            this.btnFourth.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFourth.IdleIconLeftImage = null;
            this.btnFourth.IdleIconRightImage = null;
            this.btnFourth.IndicateFocus = false;
            this.btnFourth.Location = new System.Drawing.Point(378, 3);
            this.btnFourth.Name = "btnFourth";
            this.btnFourth.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFourth.OnDisabledState.BorderRadius = 20;
            this.btnFourth.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFourth.OnDisabledState.BorderThickness = 1;
            this.btnFourth.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFourth.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFourth.OnDisabledState.IconLeftImage = null;
            this.btnFourth.OnDisabledState.IconRightImage = null;
            this.btnFourth.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnFourth.onHoverState.BorderRadius = 20;
            this.btnFourth.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFourth.onHoverState.BorderThickness = 1;
            this.btnFourth.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnFourth.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnFourth.onHoverState.IconLeftImage = null;
            this.btnFourth.onHoverState.IconRightImage = null;
            this.btnFourth.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFourth.OnIdleState.BorderRadius = 20;
            this.btnFourth.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFourth.OnIdleState.BorderThickness = 1;
            this.btnFourth.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFourth.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFourth.OnIdleState.IconLeftImage = null;
            this.btnFourth.OnIdleState.IconRightImage = null;
            this.btnFourth.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnFourth.OnPressedState.BorderRadius = 20;
            this.btnFourth.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFourth.OnPressedState.BorderThickness = 1;
            this.btnFourth.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnFourth.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnFourth.OnPressedState.IconLeftImage = null;
            this.btnFourth.OnPressedState.IconRightImage = null;
            this.btnFourth.Size = new System.Drawing.Size(115, 39);
            this.btnFourth.TabIndex = 4;
            this.btnFourth.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFourth.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFourth.TextMarginLeft = 0;
            this.btnFourth.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFourth.UseDefaultRadiusAndThickness = true;
            // 
            // btnAll
            // 
            this.btnAll.AllowAnimations = true;
            this.btnAll.AllowMouseEffects = true;
            this.btnAll.AllowToggling = false;
            this.btnAll.AnimationSpeed = 200;
            this.btnAll.AutoGenerateColors = false;
            this.btnAll.AutoRoundBorders = false;
            this.btnAll.AutoSizeLeftIcon = true;
            this.btnAll.AutoSizeRightIcon = true;
            this.btnAll.BackColor = System.Drawing.Color.Transparent;
            this.btnAll.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAll.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAll.BackgroundImage")));
            this.btnAll.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAll.ButtonText = "Todo";
            this.btnAll.ButtonTextMarginLeft = 0;
            this.btnAll.ColorContrastOnClick = 45;
            this.btnAll.ColorContrastOnHover = 45;
            this.btnAll.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnAll.CustomizableEdges = borderEdges2;
            this.btnAll.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAll.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAll.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAll.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAll.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnAll.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAll.ForeColor = System.Drawing.Color.White;
            this.btnAll.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAll.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAll.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAll.IconMarginLeft = 11;
            this.btnAll.IconPadding = 10;
            this.btnAll.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAll.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAll.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAll.IconSize = 25;
            this.btnAll.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAll.IdleBorderRadius = 20;
            this.btnAll.IdleBorderThickness = 1;
            this.btnAll.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAll.IdleIconLeftImage = null;
            this.btnAll.IdleIconRightImage = null;
            this.btnAll.IndicateFocus = false;
            this.btnAll.Location = new System.Drawing.Point(3, 3);
            this.btnAll.Name = "btnAll";
            this.btnAll.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAll.OnDisabledState.BorderRadius = 20;
            this.btnAll.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAll.OnDisabledState.BorderThickness = 1;
            this.btnAll.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAll.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAll.OnDisabledState.IconLeftImage = null;
            this.btnAll.OnDisabledState.IconRightImage = null;
            this.btnAll.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnAll.onHoverState.BorderRadius = 20;
            this.btnAll.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAll.onHoverState.BorderThickness = 1;
            this.btnAll.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnAll.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnAll.onHoverState.IconLeftImage = null;
            this.btnAll.onHoverState.IconRightImage = null;
            this.btnAll.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAll.OnIdleState.BorderRadius = 20;
            this.btnAll.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAll.OnIdleState.BorderThickness = 1;
            this.btnAll.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnAll.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAll.OnIdleState.IconLeftImage = null;
            this.btnAll.OnIdleState.IconRightImage = null;
            this.btnAll.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnAll.OnPressedState.BorderRadius = 20;
            this.btnAll.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnAll.OnPressedState.BorderThickness = 1;
            this.btnAll.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnAll.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnAll.OnPressedState.IconLeftImage = null;
            this.btnAll.OnPressedState.IconRightImage = null;
            this.btnAll.Size = new System.Drawing.Size(115, 39);
            this.btnAll.TabIndex = 5;
            this.btnAll.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAll.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAll.TextMarginLeft = 0;
            this.btnAll.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAll.UseDefaultRadiusAndThickness = true;
            // 
            // btnFirstT
            // 
            this.btnFirstT.AllowAnimations = true;
            this.btnFirstT.AllowMouseEffects = true;
            this.btnFirstT.AllowToggling = false;
            this.btnFirstT.AnimationSpeed = 200;
            this.btnFirstT.AutoGenerateColors = false;
            this.btnFirstT.AutoRoundBorders = false;
            this.btnFirstT.AutoSizeLeftIcon = true;
            this.btnFirstT.AutoSizeRightIcon = true;
            this.btnFirstT.BackColor = System.Drawing.Color.Transparent;
            this.btnFirstT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFirstT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFirstT.BackgroundImage")));
            this.btnFirstT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFirstT.ButtonText = "Primer trimestre";
            this.btnFirstT.ButtonTextMarginLeft = 0;
            this.btnFirstT.ColorContrastOnClick = 45;
            this.btnFirstT.ColorContrastOnHover = 45;
            this.btnFirstT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnFirstT.CustomizableEdges = borderEdges3;
            this.btnFirstT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFirstT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFirstT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFirstT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFirstT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnFirstT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnFirstT.ForeColor = System.Drawing.Color.White;
            this.btnFirstT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFirstT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFirstT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFirstT.IconMarginLeft = 11;
            this.btnFirstT.IconPadding = 10;
            this.btnFirstT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFirstT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFirstT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFirstT.IconSize = 25;
            this.btnFirstT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFirstT.IdleBorderRadius = 20;
            this.btnFirstT.IdleBorderThickness = 1;
            this.btnFirstT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFirstT.IdleIconLeftImage = null;
            this.btnFirstT.IdleIconRightImage = null;
            this.btnFirstT.IndicateFocus = false;
            this.btnFirstT.Location = new System.Drawing.Point(128, 3);
            this.btnFirstT.Name = "btnFirstT";
            this.btnFirstT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFirstT.OnDisabledState.BorderRadius = 20;
            this.btnFirstT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFirstT.OnDisabledState.BorderThickness = 1;
            this.btnFirstT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFirstT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFirstT.OnDisabledState.IconLeftImage = null;
            this.btnFirstT.OnDisabledState.IconRightImage = null;
            this.btnFirstT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnFirstT.onHoverState.BorderRadius = 20;
            this.btnFirstT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFirstT.onHoverState.BorderThickness = 1;
            this.btnFirstT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnFirstT.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnFirstT.onHoverState.IconLeftImage = null;
            this.btnFirstT.onHoverState.IconRightImage = null;
            this.btnFirstT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFirstT.OnIdleState.BorderRadius = 20;
            this.btnFirstT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFirstT.OnIdleState.BorderThickness = 1;
            this.btnFirstT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnFirstT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnFirstT.OnIdleState.IconLeftImage = null;
            this.btnFirstT.OnIdleState.IconRightImage = null;
            this.btnFirstT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnFirstT.OnPressedState.BorderRadius = 20;
            this.btnFirstT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnFirstT.OnPressedState.BorderThickness = 1;
            this.btnFirstT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnFirstT.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnFirstT.OnPressedState.IconLeftImage = null;
            this.btnFirstT.OnPressedState.IconRightImage = null;
            this.btnFirstT.Size = new System.Drawing.Size(115, 39);
            this.btnFirstT.TabIndex = 1;
            this.btnFirstT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnFirstT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFirstT.TextMarginLeft = 0;
            this.btnFirstT.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFirstT.UseDefaultRadiusAndThickness = true;
            // 
            // btnThirtht
            // 
            this.btnThirtht.AllowAnimations = true;
            this.btnThirtht.AllowMouseEffects = true;
            this.btnThirtht.AllowToggling = false;
            this.btnThirtht.AnimationSpeed = 200;
            this.btnThirtht.AutoGenerateColors = false;
            this.btnThirtht.AutoRoundBorders = false;
            this.btnThirtht.AutoSizeLeftIcon = true;
            this.btnThirtht.AutoSizeRightIcon = true;
            this.btnThirtht.BackColor = System.Drawing.Color.Transparent;
            this.btnThirtht.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnThirtht.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThirtht.BackgroundImage")));
            this.btnThirtht.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnThirtht.ButtonText = "Tercer trimestre";
            this.btnThirtht.ButtonTextMarginLeft = 0;
            this.btnThirtht.ColorContrastOnClick = 45;
            this.btnThirtht.ColorContrastOnHover = 45;
            this.btnThirtht.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnThirtht.CustomizableEdges = borderEdges4;
            this.btnThirtht.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThirtht.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThirtht.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThirtht.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThirtht.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnThirtht.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnThirtht.ForeColor = System.Drawing.Color.White;
            this.btnThirtht.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThirtht.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThirtht.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThirtht.IconMarginLeft = 11;
            this.btnThirtht.IconPadding = 10;
            this.btnThirtht.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThirtht.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThirtht.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThirtht.IconSize = 25;
            this.btnThirtht.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnThirtht.IdleBorderRadius = 20;
            this.btnThirtht.IdleBorderThickness = 1;
            this.btnThirtht.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnThirtht.IdleIconLeftImage = null;
            this.btnThirtht.IdleIconRightImage = null;
            this.btnThirtht.IndicateFocus = false;
            this.btnThirtht.Location = new System.Drawing.Point(503, 3);
            this.btnThirtht.Name = "btnThirtht";
            this.btnThirtht.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThirtht.OnDisabledState.BorderRadius = 20;
            this.btnThirtht.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnThirtht.OnDisabledState.BorderThickness = 1;
            this.btnThirtht.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThirtht.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThirtht.OnDisabledState.IconLeftImage = null;
            this.btnThirtht.OnDisabledState.IconRightImage = null;
            this.btnThirtht.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnThirtht.onHoverState.BorderRadius = 20;
            this.btnThirtht.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnThirtht.onHoverState.BorderThickness = 1;
            this.btnThirtht.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnThirtht.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnThirtht.onHoverState.IconLeftImage = null;
            this.btnThirtht.onHoverState.IconRightImage = null;
            this.btnThirtht.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnThirtht.OnIdleState.BorderRadius = 20;
            this.btnThirtht.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnThirtht.OnIdleState.BorderThickness = 1;
            this.btnThirtht.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnThirtht.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThirtht.OnIdleState.IconLeftImage = null;
            this.btnThirtht.OnIdleState.IconRightImage = null;
            this.btnThirtht.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnThirtht.OnPressedState.BorderRadius = 20;
            this.btnThirtht.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnThirtht.OnPressedState.BorderThickness = 1;
            this.btnThirtht.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnThirtht.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnThirtht.OnPressedState.IconLeftImage = null;
            this.btnThirtht.OnPressedState.IconRightImage = null;
            this.btnThirtht.Size = new System.Drawing.Size(117, 39);
            this.btnThirtht.TabIndex = 3;
            this.btnThirtht.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThirtht.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThirtht.TextMarginLeft = 0;
            this.btnThirtht.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThirtht.UseDefaultRadiusAndThickness = true;
            // 
            // btnSecondT
            // 
            this.btnSecondT.AllowAnimations = true;
            this.btnSecondT.AllowMouseEffects = true;
            this.btnSecondT.AllowToggling = false;
            this.btnSecondT.AnimationSpeed = 200;
            this.btnSecondT.AutoGenerateColors = false;
            this.btnSecondT.AutoRoundBorders = false;
            this.btnSecondT.AutoSizeLeftIcon = true;
            this.btnSecondT.AutoSizeRightIcon = true;
            this.btnSecondT.BackColor = System.Drawing.Color.Transparent;
            this.btnSecondT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnSecondT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSecondT.BackgroundImage")));
            this.btnSecondT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSecondT.ButtonText = "Segundo trimestre";
            this.btnSecondT.ButtonTextMarginLeft = 0;
            this.btnSecondT.ColorContrastOnClick = 45;
            this.btnSecondT.ColorContrastOnHover = 45;
            this.btnSecondT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnSecondT.CustomizableEdges = borderEdges5;
            this.btnSecondT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSecondT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSecondT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSecondT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSecondT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnSecondT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSecondT.ForeColor = System.Drawing.Color.White;
            this.btnSecondT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSecondT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSecondT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSecondT.IconMarginLeft = 11;
            this.btnSecondT.IconPadding = 10;
            this.btnSecondT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSecondT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSecondT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSecondT.IconSize = 25;
            this.btnSecondT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnSecondT.IdleBorderRadius = 20;
            this.btnSecondT.IdleBorderThickness = 1;
            this.btnSecondT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnSecondT.IdleIconLeftImage = null;
            this.btnSecondT.IdleIconRightImage = null;
            this.btnSecondT.IndicateFocus = false;
            this.btnSecondT.Location = new System.Drawing.Point(253, 3);
            this.btnSecondT.Name = "btnSecondT";
            this.btnSecondT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSecondT.OnDisabledState.BorderRadius = 20;
            this.btnSecondT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSecondT.OnDisabledState.BorderThickness = 1;
            this.btnSecondT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSecondT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSecondT.OnDisabledState.IconLeftImage = null;
            this.btnSecondT.OnDisabledState.IconRightImage = null;
            this.btnSecondT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnSecondT.onHoverState.BorderRadius = 20;
            this.btnSecondT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSecondT.onHoverState.BorderThickness = 1;
            this.btnSecondT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnSecondT.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnSecondT.onHoverState.IconLeftImage = null;
            this.btnSecondT.onHoverState.IconRightImage = null;
            this.btnSecondT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnSecondT.OnIdleState.BorderRadius = 20;
            this.btnSecondT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSecondT.OnIdleState.BorderThickness = 1;
            this.btnSecondT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.btnSecondT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSecondT.OnIdleState.IconLeftImage = null;
            this.btnSecondT.OnIdleState.IconRightImage = null;
            this.btnSecondT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnSecondT.OnPressedState.BorderRadius = 20;
            this.btnSecondT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnSecondT.OnPressedState.BorderThickness = 1;
            this.btnSecondT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(217)))), ((int)(((byte)(217)))), ((int)(((byte)(217)))));
            this.btnSecondT.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnSecondT.OnPressedState.IconLeftImage = null;
            this.btnSecondT.OnPressedState.IconRightImage = null;
            this.btnSecondT.Size = new System.Drawing.Size(115, 39);
            this.btnSecondT.TabIndex = 2;
            this.btnSecondT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSecondT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSecondT.TextMarginLeft = 0;
            this.btnSecondT.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSecondT.UseDefaultRadiusAndThickness = true;
            // 
            // picNotification
            // 
            this.picNotification.AllowFocused = false;
            this.picNotification.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.picNotification.AutoSizeHeight = false;
            this.picNotification.BorderRadius = 30;
            this.picNotification.Image = ((System.Drawing.Image)(resources.GetObject("picNotification.Image")));
            this.picNotification.IsCircle = true;
            this.picNotification.Location = new System.Drawing.Point(116, 198);
            this.picNotification.Name = "picNotification";
            this.picNotification.Size = new System.Drawing.Size(61, 61);
            this.picNotification.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.picNotification.TabIndex = 101;
            this.picNotification.TabStop = false;
            this.picNotification.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // txtSearch
            // 
            this.txtSearch.AcceptsReturn = false;
            this.txtSearch.AcceptsTab = false;
            this.txtSearch.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.txtSearch.AnimationSpeed = 200;
            this.txtSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtSearch.AutoSizeHeight = true;
            this.txtSearch.BackColor = System.Drawing.Color.Transparent;
            this.txtSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtSearch.BackgroundImage")));
            this.txtSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtSearch.BorderRadius = 20;
            this.txtSearch.BorderThickness = 1;
            this.txtSearch.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.txtSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.DefaultFont = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txtSearch.DefaultText = "";
            this.txtSearch.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            this.txtSearch.ForeColor = System.Drawing.Color.White;
            this.txtSearch.HideSelection = true;
            this.txtSearch.IconLeft = null;
            this.txtSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.IconPadding = 10;
            this.txtSearch.IconRight = ((System.Drawing.Image)(resources.GetObject("txtSearch.IconRight")));
            this.txtSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtSearch.Lines = new string[0];
            this.txtSearch.Location = new System.Drawing.Point(356, 207);
            this.txtSearch.MaxLength = 32767;
            this.txtSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtSearch.Modified = false;
            this.txtSearch.Multiline = false;
            this.txtSearch.Name = "txtSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(162)))), ((int)(((byte)(0)))), ((int)(((byte)(11)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtSearch.OnIdleState = stateProperties4;
            this.txtSearch.Padding = new System.Windows.Forms.Padding(3);
            this.txtSearch.PasswordChar = '\0';
            this.txtSearch.PlaceholderForeColor = System.Drawing.Color.White;
            this.txtSearch.PlaceholderText = "Buscador";
            this.txtSearch.ReadOnly = false;
            this.txtSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtSearch.SelectedText = "";
            this.txtSearch.SelectionLength = 0;
            this.txtSearch.SelectionStart = 0;
            this.txtSearch.ShortcutsEnabled = true;
            this.txtSearch.Size = new System.Drawing.Size(451, 37);
            this.txtSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtSearch.TabIndex = 102;
            this.txtSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtSearch.TextMarginBottom = 0;
            this.txtSearch.TextMarginLeft = 3;
            this.txtSearch.TextMarginTop = 1;
            this.txtSearch.TextPlaceholder = "Buscador";
            this.txtSearch.UseSystemPasswordChar = false;
            this.txtSearch.WordWrap = true;
            // 
            // prueba
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1162, 450);
            this.Controls.Add(this.txtSearch);
            this.Controls.Add(this.picNotification);
            this.Controls.Add(this.tableLayoutPanel17);
            this.Name = "prueba";
            this.Text = "prueba";
            this.tableLayoutPanel17.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picNotification)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel17;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnFourth;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnAll;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnFirstT;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnThirtht;
        public Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnSecondT;
        public Bunifu.UI.WinForms.BunifuPictureBox picNotification;
        public Bunifu.UI.WinForms.BunifuTextBox txtSearch;
    }
}